/zmp/loop_rate: 1000
/FL_ft_sensor_topic_name: /MELEW3/ForceSensor_foot_FL
/FR_ft_sensor_topic_name: /MELEW3/ForceSensor_foot_FR
/BL_ft_sensor_topic_name: /MELEW3/ForceSensor_foot_BL
/BR_ft_sensor_topic_name: /MELEW3/ForceSensor_foot_BR
/base_topic_name: /MELEW3/base
/com_topic_name: /MELEW3/com
/base_topic_name: /MELEW3/imu
/imaginary_zmp_topic_name: /MELEW3/imaginary_zmp
/link_info_topic_name: /MELEW3/link_info
/actual_zmp_topic_name: /MELEW3/actual_zmp
/zmp/dt: 0.001
/zmp/support_area_x_min: 0.0
/zmp/support_area_y_min: 0.0
/zmp/support_area_x_max: 0.0
/zmp/support_area_y_max: 0.0
/zmp/min_contact_force: 10.0
/zmp/ft_sensor_link_num_FL: 7
/zmp/ft_sensor_link_num_FR: 16
/zmp/ft_sensor_link_num_BL: 25
/zmp/ft_sensor_link_num_BR: 34