// Generated by gencpp from file melew3_msgs/AddMd80sResponse.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_ADDMD80SRESPONSE_H
#define MELEW3_MSGS_MESSAGE_ADDMD80SRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace melew3_msgs
{
template <class ContainerAllocator>
struct AddMd80sResponse_
{
  typedef AddMd80sResponse_<ContainerAllocator> Type;

  AddMd80sResponse_()
    : drives_success()
    , total_number_of_drives(0)  {
    }
  AddMd80sResponse_(const ContainerAllocator& _alloc)
    : drives_success(_alloc)
    , total_number_of_drives(0)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _drives_success_type;
  _drives_success_type drives_success;

   typedef uint16_t _total_number_of_drives_type;
  _total_number_of_drives_type total_number_of_drives;





  typedef boost::shared_ptr< ::melew3_msgs::AddMd80sResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::melew3_msgs::AddMd80sResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddMd80sResponse_

typedef ::melew3_msgs::AddMd80sResponse_<std::allocator<void> > AddMd80sResponse;

typedef boost::shared_ptr< ::melew3_msgs::AddMd80sResponse > AddMd80sResponsePtr;
typedef boost::shared_ptr< ::melew3_msgs::AddMd80sResponse const> AddMd80sResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::melew3_msgs::AddMd80sResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::melew3_msgs::AddMd80sResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::melew3_msgs::AddMd80sResponse_<ContainerAllocator1> & lhs, const ::melew3_msgs::AddMd80sResponse_<ContainerAllocator2> & rhs)
{
  return lhs.drives_success == rhs.drives_success &&
    lhs.total_number_of_drives == rhs.total_number_of_drives;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::melew3_msgs::AddMd80sResponse_<ContainerAllocator1> & lhs, const ::melew3_msgs::AddMd80sResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace melew3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::AddMd80sResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::AddMd80sResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::AddMd80sResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::AddMd80sResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::AddMd80sResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::AddMd80sResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::melew3_msgs::AddMd80sResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb11802d8e72df77ab2fa1c8f71e5432";
  }

  static const char* value(const ::melew3_msgs::AddMd80sResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb11802d8e72df77ULL;
  static const uint64_t static_value2 = 0xab2fa1c8f71e5432ULL;
};

template<class ContainerAllocator>
struct DataType< ::melew3_msgs::AddMd80sResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "melew3_msgs/AddMd80sResponse";
  }

  static const char* value(const ::melew3_msgs::AddMd80sResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::melew3_msgs::AddMd80sResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool[] drives_success\n"
"uint16 total_number_of_drives\n"
;
  }

  static const char* value(const ::melew3_msgs::AddMd80sResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::melew3_msgs::AddMd80sResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.drives_success);
      stream.next(m.total_number_of_drives);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddMd80sResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::melew3_msgs::AddMd80sResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::melew3_msgs::AddMd80sResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "drives_success: ";
    if (v.drives_success.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.drives_success.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.drives_success[i]);
    }
    if (v.drives_success.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "total_number_of_drives: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.total_number_of_drives);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_ADDMD80SRESPONSE_H
