// Generated by gencpp from file melew3_msgs/AddMd80s.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_ADDMD80S_H
#define MELEW3_MSGS_MESSAGE_ADDMD80S_H

#include <ros/service_traits.h>


#include <melew3_msgs/AddMd80sRequest.h>
#include <melew3_msgs/AddMd80sResponse.h>


namespace melew3_msgs
{

struct AddMd80s
{

typedef AddMd80sRequest Request;
typedef AddMd80sResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddMd80s
} // namespace melew3_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::melew3_msgs::AddMd80s > {
  static const char* value()
  {
    return "4d3ef511c44dd08dd3627532b66a574c";
  }

  static const char* value(const ::melew3_msgs::AddMd80s&) { return value(); }
};

template<>
struct DataType< ::melew3_msgs::AddMd80s > {
  static const char* value()
  {
    return "melew3_msgs/AddMd80s";
  }

  static const char* value(const ::melew3_msgs::AddMd80s&) { return value(); }
};


// service_traits::MD5Sum< ::melew3_msgs::AddMd80sRequest> should match
// service_traits::MD5Sum< ::melew3_msgs::AddMd80s >
template<>
struct MD5Sum< ::melew3_msgs::AddMd80sRequest>
{
  static const char* value()
  {
    return MD5Sum< ::melew3_msgs::AddMd80s >::value();
  }
  static const char* value(const ::melew3_msgs::AddMd80sRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::melew3_msgs::AddMd80sRequest> should match
// service_traits::DataType< ::melew3_msgs::AddMd80s >
template<>
struct DataType< ::melew3_msgs::AddMd80sRequest>
{
  static const char* value()
  {
    return DataType< ::melew3_msgs::AddMd80s >::value();
  }
  static const char* value(const ::melew3_msgs::AddMd80sRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::melew3_msgs::AddMd80sResponse> should match
// service_traits::MD5Sum< ::melew3_msgs::AddMd80s >
template<>
struct MD5Sum< ::melew3_msgs::AddMd80sResponse>
{
  static const char* value()
  {
    return MD5Sum< ::melew3_msgs::AddMd80s >::value();
  }
  static const char* value(const ::melew3_msgs::AddMd80sResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::melew3_msgs::AddMd80sResponse> should match
// service_traits::DataType< ::melew3_msgs::AddMd80s >
template<>
struct DataType< ::melew3_msgs::AddMd80sResponse>
{
  static const char* value()
  {
    return DataType< ::melew3_msgs::AddMd80s >::value();
  }
  static const char* value(const ::melew3_msgs::AddMd80sResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_ADDMD80S_H
