// Generated by gencpp from file melew3_msgs/enter_control_mode.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_ENTER_CONTROL_MODE_H
#define MELEW3_MSGS_MESSAGE_ENTER_CONTROL_MODE_H

#include <ros/service_traits.h>


#include <melew3_msgs/enter_control_modeRequest.h>
#include <melew3_msgs/enter_control_modeResponse.h>


namespace melew3_msgs
{

struct enter_control_mode
{

typedef enter_control_modeRequest Request;
typedef enter_control_modeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct enter_control_mode
} // namespace melew3_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::melew3_msgs::enter_control_mode > {
  static const char* value()
  {
    return "d1a68f1452832714a857b39d4b4ecf8d";
  }

  static const char* value(const ::melew3_msgs::enter_control_mode&) { return value(); }
};

template<>
struct DataType< ::melew3_msgs::enter_control_mode > {
  static const char* value()
  {
    return "melew3_msgs/enter_control_mode";
  }

  static const char* value(const ::melew3_msgs::enter_control_mode&) { return value(); }
};


// service_traits::MD5Sum< ::melew3_msgs::enter_control_modeRequest> should match
// service_traits::MD5Sum< ::melew3_msgs::enter_control_mode >
template<>
struct MD5Sum< ::melew3_msgs::enter_control_modeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::melew3_msgs::enter_control_mode >::value();
  }
  static const char* value(const ::melew3_msgs::enter_control_modeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::melew3_msgs::enter_control_modeRequest> should match
// service_traits::DataType< ::melew3_msgs::enter_control_mode >
template<>
struct DataType< ::melew3_msgs::enter_control_modeRequest>
{
  static const char* value()
  {
    return DataType< ::melew3_msgs::enter_control_mode >::value();
  }
  static const char* value(const ::melew3_msgs::enter_control_modeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::melew3_msgs::enter_control_modeResponse> should match
// service_traits::MD5Sum< ::melew3_msgs::enter_control_mode >
template<>
struct MD5Sum< ::melew3_msgs::enter_control_modeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::melew3_msgs::enter_control_mode >::value();
  }
  static const char* value(const ::melew3_msgs::enter_control_modeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::melew3_msgs::enter_control_modeResponse> should match
// service_traits::DataType< ::melew3_msgs::enter_control_mode >
template<>
struct DataType< ::melew3_msgs::enter_control_modeResponse>
{
  static const char* value()
  {
    return DataType< ::melew3_msgs::enter_control_mode >::value();
  }
  static const char* value(const ::melew3_msgs::enter_control_modeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_ENTER_CONTROL_MODE_H
