// Generated by gencpp from file melew3_msgs/enter_control_modeRequest.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_ENTER_CONTROL_MODEREQUEST_H
#define MELEW3_MSGS_MESSAGE_ENTER_CONTROL_MODEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace melew3_msgs
{
template <class ContainerAllocator>
struct enter_control_modeRequest_
{
  typedef enter_control_modeRequest_<ContainerAllocator> Type;

  enter_control_modeRequest_()
    : name()
    , CAN_ID(0)
    , model()  {
    }
  enter_control_modeRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , CAN_ID(0)
    , model(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef uint8_t _CAN_ID_type;
  _CAN_ID_type CAN_ID;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _model_type;
  _model_type model;





  typedef boost::shared_ptr< ::melew3_msgs::enter_control_modeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::melew3_msgs::enter_control_modeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct enter_control_modeRequest_

typedef ::melew3_msgs::enter_control_modeRequest_<std::allocator<void> > enter_control_modeRequest;

typedef boost::shared_ptr< ::melew3_msgs::enter_control_modeRequest > enter_control_modeRequestPtr;
typedef boost::shared_ptr< ::melew3_msgs::enter_control_modeRequest const> enter_control_modeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::melew3_msgs::enter_control_modeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::melew3_msgs::enter_control_modeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::melew3_msgs::enter_control_modeRequest_<ContainerAllocator1> & lhs, const ::melew3_msgs::enter_control_modeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.CAN_ID == rhs.CAN_ID &&
    lhs.model == rhs.model;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::melew3_msgs::enter_control_modeRequest_<ContainerAllocator1> & lhs, const ::melew3_msgs::enter_control_modeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace melew3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::enter_control_modeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::enter_control_modeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::enter_control_modeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::enter_control_modeRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::enter_control_modeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::enter_control_modeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::melew3_msgs::enter_control_modeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "22b73b59c9ebd8182ba8616cbfc08039";
  }

  static const char* value(const ::melew3_msgs::enter_control_modeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x22b73b59c9ebd818ULL;
  static const uint64_t static_value2 = 0x2ba8616cbfc08039ULL;
};

template<class ContainerAllocator>
struct DataType< ::melew3_msgs::enter_control_modeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "melew3_msgs/enter_control_modeRequest";
  }

  static const char* value(const ::melew3_msgs::enter_control_modeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::melew3_msgs::enter_control_modeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# CAN_ID of the motor\n"
"string name\n"
"uint8 CAN_ID\n"
"string model\n"
;
  }

  static const char* value(const ::melew3_msgs::enter_control_modeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::melew3_msgs::enter_control_modeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.CAN_ID);
      stream.next(m.model);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct enter_control_modeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::melew3_msgs::enter_control_modeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::melew3_msgs::enter_control_modeRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "CAN_ID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.CAN_ID);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "model: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.model);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_ENTER_CONTROL_MODEREQUEST_H
