// Generated by gencpp from file melew3_msgs/exit_control_modeRequest.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_EXIT_CONTROL_MODEREQUEST_H
#define MELEW3_MSGS_MESSAGE_EXIT_CONTROL_MODEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace melew3_msgs
{
template <class ContainerAllocator>
struct exit_control_modeRequest_
{
  typedef exit_control_modeRequest_<ContainerAllocator> Type;

  exit_control_modeRequest_()
    : CAN_ID(0)  {
    }
  exit_control_modeRequest_(const ContainerAllocator& _alloc)
    : CAN_ID(0)  {
  (void)_alloc;
    }



   typedef uint8_t _CAN_ID_type;
  _CAN_ID_type CAN_ID;





  typedef boost::shared_ptr< ::melew3_msgs::exit_control_modeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::melew3_msgs::exit_control_modeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct exit_control_modeRequest_

typedef ::melew3_msgs::exit_control_modeRequest_<std::allocator<void> > exit_control_modeRequest;

typedef boost::shared_ptr< ::melew3_msgs::exit_control_modeRequest > exit_control_modeRequestPtr;
typedef boost::shared_ptr< ::melew3_msgs::exit_control_modeRequest const> exit_control_modeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::melew3_msgs::exit_control_modeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::melew3_msgs::exit_control_modeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::melew3_msgs::exit_control_modeRequest_<ContainerAllocator1> & lhs, const ::melew3_msgs::exit_control_modeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.CAN_ID == rhs.CAN_ID;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::melew3_msgs::exit_control_modeRequest_<ContainerAllocator1> & lhs, const ::melew3_msgs::exit_control_modeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace melew3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::exit_control_modeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::exit_control_modeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::exit_control_modeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::exit_control_modeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::exit_control_modeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::exit_control_modeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::melew3_msgs::exit_control_modeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f930db358785fbbc5d2a0424c4fb00c8";
  }

  static const char* value(const ::melew3_msgs::exit_control_modeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf930db358785fbbcULL;
  static const uint64_t static_value2 = 0x5d2a0424c4fb00c8ULL;
};

template<class ContainerAllocator>
struct DataType< ::melew3_msgs::exit_control_modeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "melew3_msgs/exit_control_modeRequest";
  }

  static const char* value(const ::melew3_msgs::exit_control_modeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::melew3_msgs::exit_control_modeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# CAN_ID of the motor\n"
"uint8 CAN_ID\n"
;
  }

  static const char* value(const ::melew3_msgs::exit_control_modeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::melew3_msgs::exit_control_modeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.CAN_ID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct exit_control_modeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::melew3_msgs::exit_control_modeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::melew3_msgs::exit_control_modeRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "CAN_ID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.CAN_ID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_EXIT_CONTROL_MODEREQUEST_H
