// Generated by gencpp from file melew3_msgs/FallAvoidanceMotionResponse.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_FALLAVOIDANCEMOTIONRESPONSE_H
#define MELEW3_MSGS_MESSAGE_FALLAVOIDANCEMOTIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace melew3_msgs
{
template <class ContainerAllocator>
struct FallAvoidanceMotionResponse_
{
  typedef FallAvoidanceMotionResponse_<ContainerAllocator> Type;

  FallAvoidanceMotionResponse_()
    : success(false)
    , message()  {
    }
  FallAvoidanceMotionResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::melew3_msgs::FallAvoidanceMotionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::melew3_msgs::FallAvoidanceMotionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FallAvoidanceMotionResponse_

typedef ::melew3_msgs::FallAvoidanceMotionResponse_<std::allocator<void> > FallAvoidanceMotionResponse;

typedef boost::shared_ptr< ::melew3_msgs::FallAvoidanceMotionResponse > FallAvoidanceMotionResponsePtr;
typedef boost::shared_ptr< ::melew3_msgs::FallAvoidanceMotionResponse const> FallAvoidanceMotionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::melew3_msgs::FallAvoidanceMotionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::melew3_msgs::FallAvoidanceMotionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::melew3_msgs::FallAvoidanceMotionResponse_<ContainerAllocator1> & lhs, const ::melew3_msgs::FallAvoidanceMotionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::melew3_msgs::FallAvoidanceMotionResponse_<ContainerAllocator1> & lhs, const ::melew3_msgs::FallAvoidanceMotionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace melew3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::FallAvoidanceMotionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::FallAvoidanceMotionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::FallAvoidanceMotionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::FallAvoidanceMotionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::FallAvoidanceMotionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::FallAvoidanceMotionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::melew3_msgs::FallAvoidanceMotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::melew3_msgs::FallAvoidanceMotionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::melew3_msgs::FallAvoidanceMotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "melew3_msgs/FallAvoidanceMotionResponse";
  }

  static const char* value(const ::melew3_msgs::FallAvoidanceMotionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::melew3_msgs::FallAvoidanceMotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
;
  }

  static const char* value(const ::melew3_msgs::FallAvoidanceMotionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::melew3_msgs::FallAvoidanceMotionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FallAvoidanceMotionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::melew3_msgs::FallAvoidanceMotionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::melew3_msgs::FallAvoidanceMotionResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_FALLAVOIDANCEMOTIONRESPONSE_H
