// Generated by gencpp from file melew3_msgs/FallAvoidanceMotionRequest.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_FALLAVOIDANCEMOTIONREQUEST_H
#define MELEW3_MSGS_MESSAGE_FALLAVOIDANCEMOTIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float64MultiArray.h>

namespace melew3_msgs
{
template <class ContainerAllocator>
struct FallAvoidanceMotionRequest_
{
  typedef FallAvoidanceMotionRequest_<ContainerAllocator> Type;

  FallAvoidanceMotionRequest_()
    : desired_angles()
    , support_foot(false)  {
    }
  FallAvoidanceMotionRequest_(const ContainerAllocator& _alloc)
    : desired_angles(_alloc)
    , support_foot(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float64MultiArray_<ContainerAllocator>  _desired_angles_type;
  _desired_angles_type desired_angles;

   typedef uint8_t _support_foot_type;
  _support_foot_type support_foot;





  typedef boost::shared_ptr< ::melew3_msgs::FallAvoidanceMotionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::melew3_msgs::FallAvoidanceMotionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FallAvoidanceMotionRequest_

typedef ::melew3_msgs::FallAvoidanceMotionRequest_<std::allocator<void> > FallAvoidanceMotionRequest;

typedef boost::shared_ptr< ::melew3_msgs::FallAvoidanceMotionRequest > FallAvoidanceMotionRequestPtr;
typedef boost::shared_ptr< ::melew3_msgs::FallAvoidanceMotionRequest const> FallAvoidanceMotionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::melew3_msgs::FallAvoidanceMotionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::melew3_msgs::FallAvoidanceMotionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::melew3_msgs::FallAvoidanceMotionRequest_<ContainerAllocator1> & lhs, const ::melew3_msgs::FallAvoidanceMotionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.desired_angles == rhs.desired_angles &&
    lhs.support_foot == rhs.support_foot;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::melew3_msgs::FallAvoidanceMotionRequest_<ContainerAllocator1> & lhs, const ::melew3_msgs::FallAvoidanceMotionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace melew3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::FallAvoidanceMotionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::FallAvoidanceMotionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::FallAvoidanceMotionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::FallAvoidanceMotionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::FallAvoidanceMotionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::FallAvoidanceMotionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::melew3_msgs::FallAvoidanceMotionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8791d50711ac670c28b923f1a50f0b10";
  }

  static const char* value(const ::melew3_msgs::FallAvoidanceMotionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8791d50711ac670cULL;
  static const uint64_t static_value2 = 0x28b923f1a50f0b10ULL;
};

template<class ContainerAllocator>
struct DataType< ::melew3_msgs::FallAvoidanceMotionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "melew3_msgs/FallAvoidanceMotionRequest";
  }

  static const char* value(const ::melew3_msgs::FallAvoidanceMotionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::melew3_msgs::FallAvoidanceMotionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float64MultiArray desired_angles  # 目標姿勢を満たす関節角度\n"
"bool support_foot # 支持脚（false：左脚，true：右脚）\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"float64[]         data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::melew3_msgs::FallAvoidanceMotionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::melew3_msgs::FallAvoidanceMotionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.desired_angles);
      stream.next(m.support_foot);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FallAvoidanceMotionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::melew3_msgs::FallAvoidanceMotionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::melew3_msgs::FallAvoidanceMotionRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "desired_angles: ";
    Printer< ::std_msgs::Float64MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.desired_angles);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "support_foot: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.support_foot);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_FALLAVOIDANCEMOTIONREQUEST_H
