// Generated by gencpp from file melew3_msgs/FallAvoidanceMotion.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_FALLAVOIDANCEMOTION_H
#define MELEW3_MSGS_MESSAGE_FALLAVOIDANCEMOTION_H

#include <ros/service_traits.h>


#include <melew3_msgs/FallAvoidanceMotionRequest.h>
#include <melew3_msgs/FallAvoidanceMotionResponse.h>


namespace melew3_msgs
{

struct FallAvoidanceMotion
{

typedef FallAvoidanceMotionRequest Request;
typedef FallAvoidanceMotionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FallAvoidanceMotion
} // namespace melew3_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::melew3_msgs::FallAvoidanceMotion > {
  static const char* value()
  {
    return "737f56379c2098cadb78a35625cbbf12";
  }

  static const char* value(const ::melew3_msgs::FallAvoidanceMotion&) { return value(); }
};

template<>
struct DataType< ::melew3_msgs::FallAvoidanceMotion > {
  static const char* value()
  {
    return "melew3_msgs/FallAvoidanceMotion";
  }

  static const char* value(const ::melew3_msgs::FallAvoidanceMotion&) { return value(); }
};


// service_traits::MD5Sum< ::melew3_msgs::FallAvoidanceMotionRequest> should match
// service_traits::MD5Sum< ::melew3_msgs::FallAvoidanceMotion >
template<>
struct MD5Sum< ::melew3_msgs::FallAvoidanceMotionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::melew3_msgs::FallAvoidanceMotion >::value();
  }
  static const char* value(const ::melew3_msgs::FallAvoidanceMotionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::melew3_msgs::FallAvoidanceMotionRequest> should match
// service_traits::DataType< ::melew3_msgs::FallAvoidanceMotion >
template<>
struct DataType< ::melew3_msgs::FallAvoidanceMotionRequest>
{
  static const char* value()
  {
    return DataType< ::melew3_msgs::FallAvoidanceMotion >::value();
  }
  static const char* value(const ::melew3_msgs::FallAvoidanceMotionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::melew3_msgs::FallAvoidanceMotionResponse> should match
// service_traits::MD5Sum< ::melew3_msgs::FallAvoidanceMotion >
template<>
struct MD5Sum< ::melew3_msgs::FallAvoidanceMotionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::melew3_msgs::FallAvoidanceMotion >::value();
  }
  static const char* value(const ::melew3_msgs::FallAvoidanceMotionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::melew3_msgs::FallAvoidanceMotionResponse> should match
// service_traits::DataType< ::melew3_msgs::FallAvoidanceMotion >
template<>
struct DataType< ::melew3_msgs::FallAvoidanceMotionResponse>
{
  static const char* value()
  {
    return DataType< ::melew3_msgs::FallAvoidanceMotion >::value();
  }
  static const char* value(const ::melew3_msgs::FallAvoidanceMotionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_FALLAVOIDANCEMOTION_H
