// Generated by gencpp from file melew3_msgs/GenericMd80Msg.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_GENERICMD80MSG_H
#define MELEW3_MSGS_MESSAGE_GENERICMD80MSG_H

#include <ros/service_traits.h>


#include <melew3_msgs/GenericMd80MsgRequest.h>
#include <melew3_msgs/GenericMd80MsgResponse.h>


namespace melew3_msgs
{

struct GenericMd80Msg
{

typedef GenericMd80MsgRequest Request;
typedef GenericMd80MsgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GenericMd80Msg
} // namespace melew3_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::melew3_msgs::GenericMd80Msg > {
  static const char* value()
  {
    return "6cc3f83949e7e079c4afb6b3b48d05a1";
  }

  static const char* value(const ::melew3_msgs::GenericMd80Msg&) { return value(); }
};

template<>
struct DataType< ::melew3_msgs::GenericMd80Msg > {
  static const char* value()
  {
    return "melew3_msgs/GenericMd80Msg";
  }

  static const char* value(const ::melew3_msgs::GenericMd80Msg&) { return value(); }
};


// service_traits::MD5Sum< ::melew3_msgs::GenericMd80MsgRequest> should match
// service_traits::MD5Sum< ::melew3_msgs::GenericMd80Msg >
template<>
struct MD5Sum< ::melew3_msgs::GenericMd80MsgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::melew3_msgs::GenericMd80Msg >::value();
  }
  static const char* value(const ::melew3_msgs::GenericMd80MsgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::melew3_msgs::GenericMd80MsgRequest> should match
// service_traits::DataType< ::melew3_msgs::GenericMd80Msg >
template<>
struct DataType< ::melew3_msgs::GenericMd80MsgRequest>
{
  static const char* value()
  {
    return DataType< ::melew3_msgs::GenericMd80Msg >::value();
  }
  static const char* value(const ::melew3_msgs::GenericMd80MsgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::melew3_msgs::GenericMd80MsgResponse> should match
// service_traits::MD5Sum< ::melew3_msgs::GenericMd80Msg >
template<>
struct MD5Sum< ::melew3_msgs::GenericMd80MsgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::melew3_msgs::GenericMd80Msg >::value();
  }
  static const char* value(const ::melew3_msgs::GenericMd80MsgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::melew3_msgs::GenericMd80MsgResponse> should match
// service_traits::DataType< ::melew3_msgs::GenericMd80Msg >
template<>
struct DataType< ::melew3_msgs::GenericMd80MsgResponse>
{
  static const char* value()
  {
    return DataType< ::melew3_msgs::GenericMd80Msg >::value();
  }
  static const char* value(const ::melew3_msgs::GenericMd80MsgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_GENERICMD80MSG_H
