// Generated by gencpp from file melew3_msgs/GenericMd80MsgResponse.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_GENERICMD80MSGRESPONSE_H
#define MELEW3_MSGS_MESSAGE_GENERICMD80MSGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace melew3_msgs
{
template <class ContainerAllocator>
struct GenericMd80MsgResponse_
{
  typedef GenericMd80MsgResponse_<ContainerAllocator> Type;

  GenericMd80MsgResponse_()
    : drives_success()  {
    }
  GenericMd80MsgResponse_(const ContainerAllocator& _alloc)
    : drives_success(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _drives_success_type;
  _drives_success_type drives_success;





  typedef boost::shared_ptr< ::melew3_msgs::GenericMd80MsgResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::melew3_msgs::GenericMd80MsgResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GenericMd80MsgResponse_

typedef ::melew3_msgs::GenericMd80MsgResponse_<std::allocator<void> > GenericMd80MsgResponse;

typedef boost::shared_ptr< ::melew3_msgs::GenericMd80MsgResponse > GenericMd80MsgResponsePtr;
typedef boost::shared_ptr< ::melew3_msgs::GenericMd80MsgResponse const> GenericMd80MsgResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::melew3_msgs::GenericMd80MsgResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::melew3_msgs::GenericMd80MsgResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::melew3_msgs::GenericMd80MsgResponse_<ContainerAllocator1> & lhs, const ::melew3_msgs::GenericMd80MsgResponse_<ContainerAllocator2> & rhs)
{
  return lhs.drives_success == rhs.drives_success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::melew3_msgs::GenericMd80MsgResponse_<ContainerAllocator1> & lhs, const ::melew3_msgs::GenericMd80MsgResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace melew3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::GenericMd80MsgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::GenericMd80MsgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::GenericMd80MsgResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::GenericMd80MsgResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::GenericMd80MsgResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::GenericMd80MsgResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::melew3_msgs::GenericMd80MsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b30d009cfc0cfb9ca816018e07d4b44a";
  }

  static const char* value(const ::melew3_msgs::GenericMd80MsgResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb30d009cfc0cfb9cULL;
  static const uint64_t static_value2 = 0xa816018e07d4b44aULL;
};

template<class ContainerAllocator>
struct DataType< ::melew3_msgs::GenericMd80MsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "melew3_msgs/GenericMd80MsgResponse";
  }

  static const char* value(const ::melew3_msgs::GenericMd80MsgResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::melew3_msgs::GenericMd80MsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool[] drives_success\n"
;
  }

  static const char* value(const ::melew3_msgs::GenericMd80MsgResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::melew3_msgs::GenericMd80MsgResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.drives_success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GenericMd80MsgResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::melew3_msgs::GenericMd80MsgResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::melew3_msgs::GenericMd80MsgResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "drives_success: ";
    if (v.drives_success.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.drives_success.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.drives_success[i]);
    }
    if (v.drives_success.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_GENERICMD80MSGRESPONSE_H
