// Generated by gencpp from file melew3_msgs/ImpedanceCommand.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_IMPEDANCECOMMAND_H
#define MELEW3_MSGS_MESSAGE_IMPEDANCECOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace melew3_msgs
{
template <class ContainerAllocator>
struct ImpedanceCommand_
{
  typedef ImpedanceCommand_<ContainerAllocator> Type;

  ImpedanceCommand_()
    : header()
    , drive_ids()
    , kp()
    , kd()
    , max_output()  {
    }
  ImpedanceCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , drive_ids(_alloc)
    , kp(_alloc)
    , kd(_alloc)
    , max_output(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _drive_ids_type;
  _drive_ids_type drive_ids;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _kp_type;
  _kp_type kp;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _kd_type;
  _kd_type kd;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _max_output_type;
  _max_output_type max_output;





  typedef boost::shared_ptr< ::melew3_msgs::ImpedanceCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::melew3_msgs::ImpedanceCommand_<ContainerAllocator> const> ConstPtr;

}; // struct ImpedanceCommand_

typedef ::melew3_msgs::ImpedanceCommand_<std::allocator<void> > ImpedanceCommand;

typedef boost::shared_ptr< ::melew3_msgs::ImpedanceCommand > ImpedanceCommandPtr;
typedef boost::shared_ptr< ::melew3_msgs::ImpedanceCommand const> ImpedanceCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::melew3_msgs::ImpedanceCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::melew3_msgs::ImpedanceCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::melew3_msgs::ImpedanceCommand_<ContainerAllocator1> & lhs, const ::melew3_msgs::ImpedanceCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.drive_ids == rhs.drive_ids &&
    lhs.kp == rhs.kp &&
    lhs.kd == rhs.kd &&
    lhs.max_output == rhs.max_output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::melew3_msgs::ImpedanceCommand_<ContainerAllocator1> & lhs, const ::melew3_msgs::ImpedanceCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace melew3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::ImpedanceCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::ImpedanceCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::ImpedanceCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::ImpedanceCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::ImpedanceCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::ImpedanceCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::melew3_msgs::ImpedanceCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "40af67bb716e4acb3c8bc07b9bc030fd";
  }

  static const char* value(const ::melew3_msgs::ImpedanceCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x40af67bb716e4acbULL;
  static const uint64_t static_value2 = 0x3c8bc07b9bc030fdULL;
};

template<class ContainerAllocator>
struct DataType< ::melew3_msgs::ImpedanceCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "melew3_msgs/ImpedanceCommand";
  }

  static const char* value(const ::melew3_msgs::ImpedanceCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::melew3_msgs::ImpedanceCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint16[] drive_ids\n"
"float32[] kp\n"
"float32[] kd\n"
"float32[] max_output\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::melew3_msgs::ImpedanceCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::melew3_msgs::ImpedanceCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.drive_ids);
      stream.next(m.kp);
      stream.next(m.kd);
      stream.next(m.max_output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImpedanceCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::melew3_msgs::ImpedanceCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::melew3_msgs::ImpedanceCommand_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "drive_ids: ";
    if (v.drive_ids.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.drive_ids.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint16_t>::stream(s, true ? std::string() : indent + "    ", v.drive_ids[i]);
    }
    if (v.drive_ids.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "kp: ";
    if (v.kp.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.kp.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.kp[i]);
    }
    if (v.kp.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "kd: ";
    if (v.kd.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.kd.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.kd[i]);
    }
    if (v.kd.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "max_output: ";
    if (v.max_output.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.max_output.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.max_output[i]);
    }
    if (v.max_output.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_IMPEDANCECOMMAND_H
