// Generated by gencpp from file melew3_msgs/leg_pose.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_LEG_POSE_H
#define MELEW3_MSGS_MESSAGE_LEG_POSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <std_msgs/Float64.h>

namespace melew3_msgs
{
template <class ContainerAllocator>
struct leg_pose_
{
  typedef leg_pose_<ContainerAllocator> Type;

  leg_pose_()
    : header()
    , point()
    , yaw()  {
    }
  leg_pose_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , point(_alloc)
    , yaw(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _point_type;
  _point_type point;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::melew3_msgs::leg_pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::melew3_msgs::leg_pose_<ContainerAllocator> const> ConstPtr;

}; // struct leg_pose_

typedef ::melew3_msgs::leg_pose_<std::allocator<void> > leg_pose;

typedef boost::shared_ptr< ::melew3_msgs::leg_pose > leg_posePtr;
typedef boost::shared_ptr< ::melew3_msgs::leg_pose const> leg_poseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::melew3_msgs::leg_pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::melew3_msgs::leg_pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::melew3_msgs::leg_pose_<ContainerAllocator1> & lhs, const ::melew3_msgs::leg_pose_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.point == rhs.point &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::melew3_msgs::leg_pose_<ContainerAllocator1> & lhs, const ::melew3_msgs::leg_pose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace melew3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::leg_pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::leg_pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::leg_pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::leg_pose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::leg_pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::leg_pose_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::melew3_msgs::leg_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "76cd62e084d757e7a87b11d4ad219459";
  }

  static const char* value(const ::melew3_msgs::leg_pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x76cd62e084d757e7ULL;
  static const uint64_t static_value2 = 0xa87b11d4ad219459ULL;
};

template<class ContainerAllocator>
struct DataType< ::melew3_msgs::leg_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "melew3_msgs/leg_pose";
  }

  static const char* value(const ::melew3_msgs::leg_pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::melew3_msgs::leg_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"geometry_msgs/Point point\n"
"std_msgs/Float64 yaw\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
;
  }

  static const char* value(const ::melew3_msgs::leg_pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::melew3_msgs::leg_pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.point);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct leg_pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::melew3_msgs::leg_pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::melew3_msgs::leg_pose_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "point: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw: ";
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_LEG_POSE_H
