// Generated by gencpp from file melew3_msgs/leg_info_set.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_LEG_INFO_SET_H
#define MELEW3_MSGS_MESSAGE_LEG_INFO_SET_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <melew3_msgs/leg_info.h>

namespace melew3_msgs
{
template <class ContainerAllocator>
struct leg_info_set_
{
  typedef leg_info_set_<ContainerAllocator> Type;

  leg_info_set_()
    : leg()  {
    }
  leg_info_set_(const ContainerAllocator& _alloc)
    : leg(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::melew3_msgs::leg_info_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::melew3_msgs::leg_info_<ContainerAllocator> >> _leg_type;
  _leg_type leg;





  typedef boost::shared_ptr< ::melew3_msgs::leg_info_set_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::melew3_msgs::leg_info_set_<ContainerAllocator> const> ConstPtr;

}; // struct leg_info_set_

typedef ::melew3_msgs::leg_info_set_<std::allocator<void> > leg_info_set;

typedef boost::shared_ptr< ::melew3_msgs::leg_info_set > leg_info_setPtr;
typedef boost::shared_ptr< ::melew3_msgs::leg_info_set const> leg_info_setConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::melew3_msgs::leg_info_set_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::melew3_msgs::leg_info_set_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::melew3_msgs::leg_info_set_<ContainerAllocator1> & lhs, const ::melew3_msgs::leg_info_set_<ContainerAllocator2> & rhs)
{
  return lhs.leg == rhs.leg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::melew3_msgs::leg_info_set_<ContainerAllocator1> & lhs, const ::melew3_msgs::leg_info_set_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace melew3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::leg_info_set_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::leg_info_set_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::leg_info_set_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::leg_info_set_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::leg_info_set_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::leg_info_set_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::melew3_msgs::leg_info_set_<ContainerAllocator> >
{
  static const char* value()
  {
    return "60a0c1f02ecf6d55f23aa1de78f2fe2b";
  }

  static const char* value(const ::melew3_msgs::leg_info_set_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x60a0c1f02ecf6d55ULL;
  static const uint64_t static_value2 = 0xf23aa1de78f2fe2bULL;
};

template<class ContainerAllocator>
struct DataType< ::melew3_msgs::leg_info_set_<ContainerAllocator> >
{
  static const char* value()
  {
    return "melew3_msgs/leg_info_set";
  }

  static const char* value(const ::melew3_msgs::leg_info_set_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::melew3_msgs::leg_info_set_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 脚先位置のpub用\n"
"melew3_msgs/leg_info[] leg\n"
"================================================================================\n"
"MSG: melew3_msgs/leg_info\n"
"geometry_msgs/Point32 position\n"
"std_msgs/Float64 yaw\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
;
  }

  static const char* value(const ::melew3_msgs::leg_info_set_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::melew3_msgs::leg_info_set_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.leg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct leg_info_set_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::melew3_msgs::leg_info_set_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::melew3_msgs::leg_info_set_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "leg: ";
    if (v.leg.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.leg.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::melew3_msgs::leg_info_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.leg[i]);
    }
    if (v.leg.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_LEG_INFO_SET_H
