// Generated by gencpp from file melew3_msgs/leg_info.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_LEG_INFO_H
#define MELEW3_MSGS_MESSAGE_LEG_INFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point32.h>
#include <std_msgs/Float64.h>

namespace melew3_msgs
{
template <class ContainerAllocator>
struct leg_info_
{
  typedef leg_info_<ContainerAllocator> Type;

  leg_info_()
    : position()
    , yaw()  {
    }
  leg_info_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , yaw(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point32_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::melew3_msgs::leg_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::melew3_msgs::leg_info_<ContainerAllocator> const> ConstPtr;

}; // struct leg_info_

typedef ::melew3_msgs::leg_info_<std::allocator<void> > leg_info;

typedef boost::shared_ptr< ::melew3_msgs::leg_info > leg_infoPtr;
typedef boost::shared_ptr< ::melew3_msgs::leg_info const> leg_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::melew3_msgs::leg_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::melew3_msgs::leg_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::melew3_msgs::leg_info_<ContainerAllocator1> & lhs, const ::melew3_msgs::leg_info_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::melew3_msgs::leg_info_<ContainerAllocator1> & lhs, const ::melew3_msgs::leg_info_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace melew3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::leg_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::leg_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::leg_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::leg_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::leg_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::leg_info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::melew3_msgs::leg_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d4617fc0ec53327f436a5e22e15be77a";
  }

  static const char* value(const ::melew3_msgs::leg_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd4617fc0ec53327fULL;
  static const uint64_t static_value2 = 0x436a5e22e15be77aULL;
};

template<class ContainerAllocator>
struct DataType< ::melew3_msgs::leg_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "melew3_msgs/leg_info";
  }

  static const char* value(const ::melew3_msgs::leg_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::melew3_msgs::leg_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point32 position\n"
"std_msgs/Float64 yaw\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
;
  }

  static const char* value(const ::melew3_msgs::leg_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::melew3_msgs::leg_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct leg_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::melew3_msgs::leg_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::melew3_msgs::leg_info_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "position: ";
    Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw: ";
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_LEG_INFO_H
