// Generated by gencpp from file melew3_msgs/MotionCommand.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_MOTIONCOMMAND_H
#define MELEW3_MSGS_MESSAGE_MOTIONCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace melew3_msgs
{
template <class ContainerAllocator>
struct MotionCommand_
{
  typedef MotionCommand_<ContainerAllocator> Type;

  MotionCommand_()
    : header()
    , drive_ids()
    , target_position()
    , target_velocity()
    , target_torque()  {
    }
  MotionCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , drive_ids(_alloc)
    , target_position(_alloc)
    , target_velocity(_alloc)
    , target_torque(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _drive_ids_type;
  _drive_ids_type drive_ids;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _target_position_type;
  _target_position_type target_position;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _target_velocity_type;
  _target_velocity_type target_velocity;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _target_torque_type;
  _target_torque_type target_torque;





  typedef boost::shared_ptr< ::melew3_msgs::MotionCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::melew3_msgs::MotionCommand_<ContainerAllocator> const> ConstPtr;

}; // struct MotionCommand_

typedef ::melew3_msgs::MotionCommand_<std::allocator<void> > MotionCommand;

typedef boost::shared_ptr< ::melew3_msgs::MotionCommand > MotionCommandPtr;
typedef boost::shared_ptr< ::melew3_msgs::MotionCommand const> MotionCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::melew3_msgs::MotionCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::melew3_msgs::MotionCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::melew3_msgs::MotionCommand_<ContainerAllocator1> & lhs, const ::melew3_msgs::MotionCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.drive_ids == rhs.drive_ids &&
    lhs.target_position == rhs.target_position &&
    lhs.target_velocity == rhs.target_velocity &&
    lhs.target_torque == rhs.target_torque;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::melew3_msgs::MotionCommand_<ContainerAllocator1> & lhs, const ::melew3_msgs::MotionCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace melew3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::MotionCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::MotionCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::MotionCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::MotionCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::MotionCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::MotionCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::melew3_msgs::MotionCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3f2b5bb30e5e58d7a8bf6136b909823";
  }

  static const char* value(const ::melew3_msgs::MotionCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3f2b5bb30e5e58dULL;
  static const uint64_t static_value2 = 0x7a8bf6136b909823ULL;
};

template<class ContainerAllocator>
struct DataType< ::melew3_msgs::MotionCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "melew3_msgs/MotionCommand";
  }

  static const char* value(const ::melew3_msgs::MotionCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::melew3_msgs::MotionCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint16[] drive_ids\n"
"float32[] target_position\n"
"float32[] target_velocity\n"
"float32[] target_torque\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::melew3_msgs::MotionCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::melew3_msgs::MotionCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.drive_ids);
      stream.next(m.target_position);
      stream.next(m.target_velocity);
      stream.next(m.target_torque);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotionCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::melew3_msgs::MotionCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::melew3_msgs::MotionCommand_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "drive_ids: ";
    if (v.drive_ids.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.drive_ids.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint16_t>::stream(s, true ? std::string() : indent + "    ", v.drive_ids[i]);
    }
    if (v.drive_ids.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_position: ";
    if (v.target_position.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.target_position.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.target_position[i]);
    }
    if (v.target_position.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_velocity: ";
    if (v.target_velocity.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.target_velocity.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.target_velocity[i]);
    }
    if (v.target_velocity.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_torque: ";
    if (v.target_torque.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.target_torque.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.target_torque[i]);
    }
    if (v.target_torque.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_MOTIONCOMMAND_H
