// Generated by gencpp from file melew3_msgs/motor_info.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_MOTOR_INFO_H
#define MELEW3_MSGS_MESSAGE_MOTOR_INFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace melew3_msgs
{
template <class ContainerAllocator>
struct motor_info_
{
  typedef motor_info_<ContainerAllocator> Type;

  motor_info_()
    : name()
    , can_id(0)  {
    }
  motor_info_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , can_id(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef uint8_t _can_id_type;
  _can_id_type can_id;





  typedef boost::shared_ptr< ::melew3_msgs::motor_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::melew3_msgs::motor_info_<ContainerAllocator> const> ConstPtr;

}; // struct motor_info_

typedef ::melew3_msgs::motor_info_<std::allocator<void> > motor_info;

typedef boost::shared_ptr< ::melew3_msgs::motor_info > motor_infoPtr;
typedef boost::shared_ptr< ::melew3_msgs::motor_info const> motor_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::melew3_msgs::motor_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::melew3_msgs::motor_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::melew3_msgs::motor_info_<ContainerAllocator1> & lhs, const ::melew3_msgs::motor_info_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.can_id == rhs.can_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::melew3_msgs::motor_info_<ContainerAllocator1> & lhs, const ::melew3_msgs::motor_info_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace melew3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::motor_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::motor_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::motor_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::motor_info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::motor_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::motor_info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::melew3_msgs::motor_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "210d22ee910a155365074b193e163d8b";
  }

  static const char* value(const ::melew3_msgs::motor_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x210d22ee910a1553ULL;
  static const uint64_t static_value2 = 0x65074b193e163d8bULL;
};

template<class ContainerAllocator>
struct DataType< ::melew3_msgs::motor_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "melew3_msgs/motor_info";
  }

  static const char* value(const ::melew3_msgs::motor_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::melew3_msgs::motor_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Information for the motor to use\n"
"string name\n"
"uint8 can_id\n"
;
  }

  static const char* value(const ::melew3_msgs::motor_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::melew3_msgs::motor_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.can_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motor_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::melew3_msgs::motor_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::melew3_msgs::motor_info_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "can_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.can_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_MOTOR_INFO_H
