// Generated by gencpp from file melew3_msgs/robot_config.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_ROBOT_CONFIG_H
#define MELEW3_MSGS_MESSAGE_ROBOT_CONFIG_H

#include <ros/service_traits.h>


#include <melew3_msgs/robot_configRequest.h>
#include <melew3_msgs/robot_configResponse.h>


namespace melew3_msgs
{

struct robot_config
{

typedef robot_configRequest Request;
typedef robot_configResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_config
} // namespace melew3_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::melew3_msgs::robot_config > {
  static const char* value()
  {
    return "d0ea6905ae3e9bf592297d448a99911d";
  }

  static const char* value(const ::melew3_msgs::robot_config&) { return value(); }
};

template<>
struct DataType< ::melew3_msgs::robot_config > {
  static const char* value()
  {
    return "melew3_msgs/robot_config";
  }

  static const char* value(const ::melew3_msgs::robot_config&) { return value(); }
};


// service_traits::MD5Sum< ::melew3_msgs::robot_configRequest> should match
// service_traits::MD5Sum< ::melew3_msgs::robot_config >
template<>
struct MD5Sum< ::melew3_msgs::robot_configRequest>
{
  static const char* value()
  {
    return MD5Sum< ::melew3_msgs::robot_config >::value();
  }
  static const char* value(const ::melew3_msgs::robot_configRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::melew3_msgs::robot_configRequest> should match
// service_traits::DataType< ::melew3_msgs::robot_config >
template<>
struct DataType< ::melew3_msgs::robot_configRequest>
{
  static const char* value()
  {
    return DataType< ::melew3_msgs::robot_config >::value();
  }
  static const char* value(const ::melew3_msgs::robot_configRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::melew3_msgs::robot_configResponse> should match
// service_traits::MD5Sum< ::melew3_msgs::robot_config >
template<>
struct MD5Sum< ::melew3_msgs::robot_configResponse>
{
  static const char* value()
  {
    return MD5Sum< ::melew3_msgs::robot_config >::value();
  }
  static const char* value(const ::melew3_msgs::robot_configResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::melew3_msgs::robot_configResponse> should match
// service_traits::DataType< ::melew3_msgs::robot_config >
template<>
struct DataType< ::melew3_msgs::robot_configResponse>
{
  static const char* value()
  {
    return DataType< ::melew3_msgs::robot_config >::value();
  }
  static const char* value(const ::melew3_msgs::robot_configResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_ROBOT_CONFIG_H
