// Generated by gencpp from file melew3_msgs/robot_configRequest.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_ROBOT_CONFIGREQUEST_H
#define MELEW3_MSGS_MESSAGE_ROBOT_CONFIGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <melew3_msgs/motor_info.h>

namespace melew3_msgs
{
template <class ContainerAllocator>
struct robot_configRequest_
{
  typedef robot_configRequest_<ContainerAllocator> Type;

  robot_configRequest_()
    : motor()  {
    }
  robot_configRequest_(const ContainerAllocator& _alloc)
    : motor(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::melew3_msgs::motor_info_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::melew3_msgs::motor_info_<ContainerAllocator> >> _motor_type;
  _motor_type motor;





  typedef boost::shared_ptr< ::melew3_msgs::robot_configRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::melew3_msgs::robot_configRequest_<ContainerAllocator> const> ConstPtr;

}; // struct robot_configRequest_

typedef ::melew3_msgs::robot_configRequest_<std::allocator<void> > robot_configRequest;

typedef boost::shared_ptr< ::melew3_msgs::robot_configRequest > robot_configRequestPtr;
typedef boost::shared_ptr< ::melew3_msgs::robot_configRequest const> robot_configRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::melew3_msgs::robot_configRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::melew3_msgs::robot_configRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::melew3_msgs::robot_configRequest_<ContainerAllocator1> & lhs, const ::melew3_msgs::robot_configRequest_<ContainerAllocator2> & rhs)
{
  return lhs.motor == rhs.motor;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::melew3_msgs::robot_configRequest_<ContainerAllocator1> & lhs, const ::melew3_msgs::robot_configRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace melew3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::robot_configRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::robot_configRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::robot_configRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::robot_configRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::robot_configRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::robot_configRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::melew3_msgs::robot_configRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2c92bad7cfc0d8a1f6189c76b43a561a";
  }

  static const char* value(const ::melew3_msgs::robot_configRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2c92bad7cfc0d8a1ULL;
  static const uint64_t static_value2 = 0xf6189c76b43a561aULL;
};

template<class ContainerAllocator>
struct DataType< ::melew3_msgs::robot_configRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "melew3_msgs/robot_configRequest";
  }

  static const char* value(const ::melew3_msgs::robot_configRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::melew3_msgs::robot_configRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Information for robot to be passed to the microcontroller\n"
"melew3_msgs/motor_info[] motor\n"
"\n"
"================================================================================\n"
"MSG: melew3_msgs/motor_info\n"
"# Information for the motor to use\n"
"string name\n"
"uint8 can_id\n"
;
  }

  static const char* value(const ::melew3_msgs::robot_configRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::melew3_msgs::robot_configRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_configRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::melew3_msgs::robot_configRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::melew3_msgs::robot_configRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "motor: ";
    if (v.motor.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.motor.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::melew3_msgs::motor_info_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.motor[i]);
    }
    if (v.motor.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_ROBOT_CONFIGREQUEST_H
