// Generated by gencpp from file melew3_msgs/robot_configResponse.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_ROBOT_CONFIGRESPONSE_H
#define MELEW3_MSGS_MESSAGE_ROBOT_CONFIGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace melew3_msgs
{
template <class ContainerAllocator>
struct robot_configResponse_
{
  typedef robot_configResponse_<ContainerAllocator> Type;

  robot_configResponse_()
    : motor_quantity(0)
    , checksum(0)  {
    }
  robot_configResponse_(const ContainerAllocator& _alloc)
    : motor_quantity(0)
    , checksum(0)  {
  (void)_alloc;
    }



   typedef uint8_t _motor_quantity_type;
  _motor_quantity_type motor_quantity;

   typedef uint8_t _checksum_type;
  _checksum_type checksum;





  typedef boost::shared_ptr< ::melew3_msgs::robot_configResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::melew3_msgs::robot_configResponse_<ContainerAllocator> const> ConstPtr;

}; // struct robot_configResponse_

typedef ::melew3_msgs::robot_configResponse_<std::allocator<void> > robot_configResponse;

typedef boost::shared_ptr< ::melew3_msgs::robot_configResponse > robot_configResponsePtr;
typedef boost::shared_ptr< ::melew3_msgs::robot_configResponse const> robot_configResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::melew3_msgs::robot_configResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::melew3_msgs::robot_configResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::melew3_msgs::robot_configResponse_<ContainerAllocator1> & lhs, const ::melew3_msgs::robot_configResponse_<ContainerAllocator2> & rhs)
{
  return lhs.motor_quantity == rhs.motor_quantity &&
    lhs.checksum == rhs.checksum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::melew3_msgs::robot_configResponse_<ContainerAllocator1> & lhs, const ::melew3_msgs::robot_configResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace melew3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::robot_configResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::robot_configResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::robot_configResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::robot_configResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::robot_configResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::robot_configResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::melew3_msgs::robot_configResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bdd1d5c3a24f0bb18e3657f15e56ddf5";
  }

  static const char* value(const ::melew3_msgs::robot_configResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbdd1d5c3a24f0bb1ULL;
  static const uint64_t static_value2 = 0x8e3657f15e56ddf5ULL;
};

template<class ContainerAllocator>
struct DataType< ::melew3_msgs::robot_configResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "melew3_msgs/robot_configResponse";
  }

  static const char* value(const ::melew3_msgs::robot_configResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::melew3_msgs::robot_configResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 motor_quantity\n"
"uint8 checksum\n"
;
  }

  static const char* value(const ::melew3_msgs::robot_configResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::melew3_msgs::robot_configResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor_quantity);
      stream.next(m.checksum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_configResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::melew3_msgs::robot_configResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::melew3_msgs::robot_configResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "motor_quantity: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motor_quantity);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "checksum: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.checksum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_ROBOT_CONFIGRESPONSE_H
