// Generated by gencpp from file melew3_msgs/servo_setting.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_SERVO_SETTING_H
#define MELEW3_MSGS_MESSAGE_SERVO_SETTING_H

#include <ros/service_traits.h>


#include <melew3_msgs/servo_settingRequest.h>
#include <melew3_msgs/servo_settingResponse.h>


namespace melew3_msgs
{

struct servo_setting
{

typedef servo_settingRequest Request;
typedef servo_settingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct servo_setting
} // namespace melew3_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::melew3_msgs::servo_setting > {
  static const char* value()
  {
    return "40ae7cc676163ebf2724cc24e1fb1718";
  }

  static const char* value(const ::melew3_msgs::servo_setting&) { return value(); }
};

template<>
struct DataType< ::melew3_msgs::servo_setting > {
  static const char* value()
  {
    return "melew3_msgs/servo_setting";
  }

  static const char* value(const ::melew3_msgs::servo_setting&) { return value(); }
};


// service_traits::MD5Sum< ::melew3_msgs::servo_settingRequest> should match
// service_traits::MD5Sum< ::melew3_msgs::servo_setting >
template<>
struct MD5Sum< ::melew3_msgs::servo_settingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::melew3_msgs::servo_setting >::value();
  }
  static const char* value(const ::melew3_msgs::servo_settingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::melew3_msgs::servo_settingRequest> should match
// service_traits::DataType< ::melew3_msgs::servo_setting >
template<>
struct DataType< ::melew3_msgs::servo_settingRequest>
{
  static const char* value()
  {
    return DataType< ::melew3_msgs::servo_setting >::value();
  }
  static const char* value(const ::melew3_msgs::servo_settingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::melew3_msgs::servo_settingResponse> should match
// service_traits::MD5Sum< ::melew3_msgs::servo_setting >
template<>
struct MD5Sum< ::melew3_msgs::servo_settingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::melew3_msgs::servo_setting >::value();
  }
  static const char* value(const ::melew3_msgs::servo_settingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::melew3_msgs::servo_settingResponse> should match
// service_traits::DataType< ::melew3_msgs::servo_setting >
template<>
struct DataType< ::melew3_msgs::servo_settingResponse>
{
  static const char* value()
  {
    return DataType< ::melew3_msgs::servo_setting >::value();
  }
  static const char* value(const ::melew3_msgs::servo_settingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_SERVO_SETTING_H
