// Generated by gencpp from file melew3_msgs/servo_settingRequest.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_SERVO_SETTINGREQUEST_H
#define MELEW3_MSGS_MESSAGE_SERVO_SETTINGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace melew3_msgs
{
template <class ContainerAllocator>
struct servo_settingRequest_
{
  typedef servo_settingRequest_<ContainerAllocator> Type;

  servo_settingRequest_()
    : name()
    , servo(false)  {
    }
  servo_settingRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , servo(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef uint8_t _servo_type;
  _servo_type servo;





  typedef boost::shared_ptr< ::melew3_msgs::servo_settingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::melew3_msgs::servo_settingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct servo_settingRequest_

typedef ::melew3_msgs::servo_settingRequest_<std::allocator<void> > servo_settingRequest;

typedef boost::shared_ptr< ::melew3_msgs::servo_settingRequest > servo_settingRequestPtr;
typedef boost::shared_ptr< ::melew3_msgs::servo_settingRequest const> servo_settingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::melew3_msgs::servo_settingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::melew3_msgs::servo_settingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::melew3_msgs::servo_settingRequest_<ContainerAllocator1> & lhs, const ::melew3_msgs::servo_settingRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.servo == rhs.servo;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::melew3_msgs::servo_settingRequest_<ContainerAllocator1> & lhs, const ::melew3_msgs::servo_settingRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace melew3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::servo_settingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::servo_settingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::servo_settingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::servo_settingRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::servo_settingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::servo_settingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::melew3_msgs::servo_settingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9ee2b5562ba69f8fdd699d7e8fdccafc";
  }

  static const char* value(const ::melew3_msgs::servo_settingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9ee2b5562ba69f8fULL;
  static const uint64_t static_value2 = 0xdd699d7e8fdccafcULL;
};

template<class ContainerAllocator>
struct DataType< ::melew3_msgs::servo_settingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "melew3_msgs/servo_settingRequest";
  }

  static const char* value(const ::melew3_msgs::servo_settingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::melew3_msgs::servo_settingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# CAN_ID of the motor\n"
"string name\n"
"bool servo\n"
;
  }

  static const char* value(const ::melew3_msgs::servo_settingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::melew3_msgs::servo_settingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.servo);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct servo_settingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::melew3_msgs::servo_settingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::melew3_msgs::servo_settingRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "servo: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.servo);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_SERVO_SETTINGREQUEST_H
