// Generated by gencpp from file melew3_msgs/set_position_zeroRequest.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_SET_POSITION_ZEROREQUEST_H
#define MELEW3_MSGS_MESSAGE_SET_POSITION_ZEROREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace melew3_msgs
{
template <class ContainerAllocator>
struct set_position_zeroRequest_
{
  typedef set_position_zeroRequest_<ContainerAllocator> Type;

  set_position_zeroRequest_()
    : name()  {
    }
  set_position_zeroRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::melew3_msgs::set_position_zeroRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::melew3_msgs::set_position_zeroRequest_<ContainerAllocator> const> ConstPtr;

}; // struct set_position_zeroRequest_

typedef ::melew3_msgs::set_position_zeroRequest_<std::allocator<void> > set_position_zeroRequest;

typedef boost::shared_ptr< ::melew3_msgs::set_position_zeroRequest > set_position_zeroRequestPtr;
typedef boost::shared_ptr< ::melew3_msgs::set_position_zeroRequest const> set_position_zeroRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::melew3_msgs::set_position_zeroRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::melew3_msgs::set_position_zeroRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::melew3_msgs::set_position_zeroRequest_<ContainerAllocator1> & lhs, const ::melew3_msgs::set_position_zeroRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::melew3_msgs::set_position_zeroRequest_<ContainerAllocator1> & lhs, const ::melew3_msgs::set_position_zeroRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace melew3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::set_position_zeroRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::set_position_zeroRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::set_position_zeroRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::set_position_zeroRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::set_position_zeroRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::set_position_zeroRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::melew3_msgs::set_position_zeroRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::melew3_msgs::set_position_zeroRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1f3d28f1b044c87ULL;
  static const uint64_t static_value2 = 0x1e6eff2e9fc3c667ULL;
};

template<class ContainerAllocator>
struct DataType< ::melew3_msgs::set_position_zeroRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "melew3_msgs/set_position_zeroRequest";
  }

  static const char* value(const ::melew3_msgs::set_position_zeroRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::melew3_msgs::set_position_zeroRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# CAN_ID of the motor\n"
"string name\n"
;
  }

  static const char* value(const ::melew3_msgs::set_position_zeroRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::melew3_msgs::set_position_zeroRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_position_zeroRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::melew3_msgs::set_position_zeroRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::melew3_msgs::set_position_zeroRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_SET_POSITION_ZEROREQUEST_H
