// Generated by gencpp from file melew3_msgs/set_pd_gainResponse.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_SET_PD_GAINRESPONSE_H
#define MELEW3_MSGS_MESSAGE_SET_PD_GAINRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace melew3_msgs
{
template <class ContainerAllocator>
struct set_pd_gainResponse_
{
  typedef set_pd_gainResponse_<ContainerAllocator> Type;

  set_pd_gainResponse_()
    : success(false)  {
    }
  set_pd_gainResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::melew3_msgs::set_pd_gainResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::melew3_msgs::set_pd_gainResponse_<ContainerAllocator> const> ConstPtr;

}; // struct set_pd_gainResponse_

typedef ::melew3_msgs::set_pd_gainResponse_<std::allocator<void> > set_pd_gainResponse;

typedef boost::shared_ptr< ::melew3_msgs::set_pd_gainResponse > set_pd_gainResponsePtr;
typedef boost::shared_ptr< ::melew3_msgs::set_pd_gainResponse const> set_pd_gainResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::melew3_msgs::set_pd_gainResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::melew3_msgs::set_pd_gainResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::melew3_msgs::set_pd_gainResponse_<ContainerAllocator1> & lhs, const ::melew3_msgs::set_pd_gainResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::melew3_msgs::set_pd_gainResponse_<ContainerAllocator1> & lhs, const ::melew3_msgs::set_pd_gainResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace melew3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::set_pd_gainResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::set_pd_gainResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::set_pd_gainResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::set_pd_gainResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::set_pd_gainResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::set_pd_gainResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::melew3_msgs::set_pd_gainResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::melew3_msgs::set_pd_gainResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::melew3_msgs::set_pd_gainResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "melew3_msgs/set_pd_gainResponse";
  }

  static const char* value(const ::melew3_msgs::set_pd_gainResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::melew3_msgs::set_pd_gainResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Whether if configuration success\n"
"bool success\n"
;
  }

  static const char* value(const ::melew3_msgs::set_pd_gainResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::melew3_msgs::set_pd_gainResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_pd_gainResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::melew3_msgs::set_pd_gainResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::melew3_msgs::set_pd_gainResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_SET_PD_GAINRESPONSE_H
