// Generated by gencpp from file melew3_msgs/set_pd_gainRequest.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_SET_PD_GAINREQUEST_H
#define MELEW3_MSGS_MESSAGE_SET_PD_GAINREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace melew3_msgs
{
template <class ContainerAllocator>
struct set_pd_gainRequest_
{
  typedef set_pd_gainRequest_<ContainerAllocator> Type;

  set_pd_gainRequest_()
    : mode(false)  {
    }
  set_pd_gainRequest_(const ContainerAllocator& _alloc)
    : mode(false)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::melew3_msgs::set_pd_gainRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::melew3_msgs::set_pd_gainRequest_<ContainerAllocator> const> ConstPtr;

}; // struct set_pd_gainRequest_

typedef ::melew3_msgs::set_pd_gainRequest_<std::allocator<void> > set_pd_gainRequest;

typedef boost::shared_ptr< ::melew3_msgs::set_pd_gainRequest > set_pd_gainRequestPtr;
typedef boost::shared_ptr< ::melew3_msgs::set_pd_gainRequest const> set_pd_gainRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::melew3_msgs::set_pd_gainRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::melew3_msgs::set_pd_gainRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::melew3_msgs::set_pd_gainRequest_<ContainerAllocator1> & lhs, const ::melew3_msgs::set_pd_gainRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::melew3_msgs::set_pd_gainRequest_<ContainerAllocator1> & lhs, const ::melew3_msgs::set_pd_gainRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace melew3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::set_pd_gainRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::set_pd_gainRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::set_pd_gainRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::set_pd_gainRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::set_pd_gainRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::set_pd_gainRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::melew3_msgs::set_pd_gainRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3124ebba8ebedcd8ba82847d482ceb7";
  }

  static const char* value(const ::melew3_msgs::set_pd_gainRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3124ebba8ebedcdULL;
  static const uint64_t static_value2 = 0x8ba82847d482ceb7ULL;
};

template<class ContainerAllocator>
struct DataType< ::melew3_msgs::set_pd_gainRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "melew3_msgs/set_pd_gainRequest";
  }

  static const char* value(const ::melew3_msgs::set_pd_gainRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::melew3_msgs::set_pd_gainRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# enable/disable\n"
"bool mode\n"
;
  }

  static const char* value(const ::melew3_msgs::set_pd_gainRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::melew3_msgs::set_pd_gainRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_pd_gainRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::melew3_msgs::set_pd_gainRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::melew3_msgs::set_pd_gainRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_SET_PD_GAINREQUEST_H
