// Generated by gencpp from file melew3_msgs/set_pd_gain.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_SET_PD_GAIN_H
#define MELEW3_MSGS_MESSAGE_SET_PD_GAIN_H

#include <ros/service_traits.h>


#include <melew3_msgs/set_pd_gainRequest.h>
#include <melew3_msgs/set_pd_gainResponse.h>


namespace melew3_msgs
{

struct set_pd_gain
{

typedef set_pd_gainRequest Request;
typedef set_pd_gainResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_pd_gain
} // namespace melew3_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::melew3_msgs::set_pd_gain > {
  static const char* value()
  {
    return "a585292d7f5827a6441e76e5026dbae6";
  }

  static const char* value(const ::melew3_msgs::set_pd_gain&) { return value(); }
};

template<>
struct DataType< ::melew3_msgs::set_pd_gain > {
  static const char* value()
  {
    return "melew3_msgs/set_pd_gain";
  }

  static const char* value(const ::melew3_msgs::set_pd_gain&) { return value(); }
};


// service_traits::MD5Sum< ::melew3_msgs::set_pd_gainRequest> should match
// service_traits::MD5Sum< ::melew3_msgs::set_pd_gain >
template<>
struct MD5Sum< ::melew3_msgs::set_pd_gainRequest>
{
  static const char* value()
  {
    return MD5Sum< ::melew3_msgs::set_pd_gain >::value();
  }
  static const char* value(const ::melew3_msgs::set_pd_gainRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::melew3_msgs::set_pd_gainRequest> should match
// service_traits::DataType< ::melew3_msgs::set_pd_gain >
template<>
struct DataType< ::melew3_msgs::set_pd_gainRequest>
{
  static const char* value()
  {
    return DataType< ::melew3_msgs::set_pd_gain >::value();
  }
  static const char* value(const ::melew3_msgs::set_pd_gainRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::melew3_msgs::set_pd_gainResponse> should match
// service_traits::MD5Sum< ::melew3_msgs::set_pd_gain >
template<>
struct MD5Sum< ::melew3_msgs::set_pd_gainResponse>
{
  static const char* value()
  {
    return MD5Sum< ::melew3_msgs::set_pd_gain >::value();
  }
  static const char* value(const ::melew3_msgs::set_pd_gainResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::melew3_msgs::set_pd_gainResponse> should match
// service_traits::DataType< ::melew3_msgs::set_pd_gain >
template<>
struct DataType< ::melew3_msgs::set_pd_gainResponse>
{
  static const char* value()
  {
    return DataType< ::melew3_msgs::set_pd_gain >::value();
  }
  static const char* value(const ::melew3_msgs::set_pd_gainResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_SET_PD_GAIN_H
