// Generated by gencpp from file melew3_msgs/set_position_zero.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_SET_POSITION_ZERO_H
#define MELEW3_MSGS_MESSAGE_SET_POSITION_ZERO_H

#include <ros/service_traits.h>


#include <melew3_msgs/set_position_zeroRequest.h>
#include <melew3_msgs/set_position_zeroResponse.h>


namespace melew3_msgs
{

struct set_position_zero
{

typedef set_position_zeroRequest Request;
typedef set_position_zeroResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_position_zero
} // namespace melew3_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::melew3_msgs::set_position_zero > {
  static const char* value()
  {
    return "d08a3b641c2f8680fbdfb1ea2e17a3e1";
  }

  static const char* value(const ::melew3_msgs::set_position_zero&) { return value(); }
};

template<>
struct DataType< ::melew3_msgs::set_position_zero > {
  static const char* value()
  {
    return "melew3_msgs/set_position_zero";
  }

  static const char* value(const ::melew3_msgs::set_position_zero&) { return value(); }
};


// service_traits::MD5Sum< ::melew3_msgs::set_position_zeroRequest> should match
// service_traits::MD5Sum< ::melew3_msgs::set_position_zero >
template<>
struct MD5Sum< ::melew3_msgs::set_position_zeroRequest>
{
  static const char* value()
  {
    return MD5Sum< ::melew3_msgs::set_position_zero >::value();
  }
  static const char* value(const ::melew3_msgs::set_position_zeroRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::melew3_msgs::set_position_zeroRequest> should match
// service_traits::DataType< ::melew3_msgs::set_position_zero >
template<>
struct DataType< ::melew3_msgs::set_position_zeroRequest>
{
  static const char* value()
  {
    return DataType< ::melew3_msgs::set_position_zero >::value();
  }
  static const char* value(const ::melew3_msgs::set_position_zeroRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::melew3_msgs::set_position_zeroResponse> should match
// service_traits::MD5Sum< ::melew3_msgs::set_position_zero >
template<>
struct MD5Sum< ::melew3_msgs::set_position_zeroResponse>
{
  static const char* value()
  {
    return MD5Sum< ::melew3_msgs::set_position_zero >::value();
  }
  static const char* value(const ::melew3_msgs::set_position_zeroResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::melew3_msgs::set_position_zeroResponse> should match
// service_traits::DataType< ::melew3_msgs::set_position_zero >
template<>
struct DataType< ::melew3_msgs::set_position_zeroResponse>
{
  static const char* value()
  {
    return DataType< ::melew3_msgs::set_position_zero >::value();
  }
  static const char* value(const ::melew3_msgs::set_position_zeroResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_SET_POSITION_ZERO_H
