// Generated by gencpp from file melew3_msgs/SetLimitsMd80.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_SETLIMITSMD80_H
#define MELEW3_MSGS_MESSAGE_SETLIMITSMD80_H

#include <ros/service_traits.h>


#include <melew3_msgs/SetLimitsMd80Request.h>
#include <melew3_msgs/SetLimitsMd80Response.h>


namespace melew3_msgs
{

struct SetLimitsMd80
{

typedef SetLimitsMd80Request Request;
typedef SetLimitsMd80Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLimitsMd80
} // namespace melew3_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::melew3_msgs::SetLimitsMd80 > {
  static const char* value()
  {
    return "8b812c4224ab59c832e9c192ff752c8d";
  }

  static const char* value(const ::melew3_msgs::SetLimitsMd80&) { return value(); }
};

template<>
struct DataType< ::melew3_msgs::SetLimitsMd80 > {
  static const char* value()
  {
    return "melew3_msgs/SetLimitsMd80";
  }

  static const char* value(const ::melew3_msgs::SetLimitsMd80&) { return value(); }
};


// service_traits::MD5Sum< ::melew3_msgs::SetLimitsMd80Request> should match
// service_traits::MD5Sum< ::melew3_msgs::SetLimitsMd80 >
template<>
struct MD5Sum< ::melew3_msgs::SetLimitsMd80Request>
{
  static const char* value()
  {
    return MD5Sum< ::melew3_msgs::SetLimitsMd80 >::value();
  }
  static const char* value(const ::melew3_msgs::SetLimitsMd80Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::melew3_msgs::SetLimitsMd80Request> should match
// service_traits::DataType< ::melew3_msgs::SetLimitsMd80 >
template<>
struct DataType< ::melew3_msgs::SetLimitsMd80Request>
{
  static const char* value()
  {
    return DataType< ::melew3_msgs::SetLimitsMd80 >::value();
  }
  static const char* value(const ::melew3_msgs::SetLimitsMd80Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::melew3_msgs::SetLimitsMd80Response> should match
// service_traits::MD5Sum< ::melew3_msgs::SetLimitsMd80 >
template<>
struct MD5Sum< ::melew3_msgs::SetLimitsMd80Response>
{
  static const char* value()
  {
    return MD5Sum< ::melew3_msgs::SetLimitsMd80 >::value();
  }
  static const char* value(const ::melew3_msgs::SetLimitsMd80Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::melew3_msgs::SetLimitsMd80Response> should match
// service_traits::DataType< ::melew3_msgs::SetLimitsMd80 >
template<>
struct DataType< ::melew3_msgs::SetLimitsMd80Response>
{
  static const char* value()
  {
    return DataType< ::melew3_msgs::SetLimitsMd80 >::value();
  }
  static const char* value(const ::melew3_msgs::SetLimitsMd80Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_SETLIMITSMD80_H
