// Generated by gencpp from file melew3_msgs/SetLimitsMd80Request.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_SETLIMITSMD80REQUEST_H
#define MELEW3_MSGS_MESSAGE_SETLIMITSMD80REQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace melew3_msgs
{
template <class ContainerAllocator>
struct SetLimitsMd80Request_
{
  typedef SetLimitsMd80Request_<ContainerAllocator> Type;

  SetLimitsMd80Request_()
    : drive_ids()
    , velocity_limit()
    , torque_limit()  {
    }
  SetLimitsMd80Request_(const ContainerAllocator& _alloc)
    : drive_ids(_alloc)
    , velocity_limit(_alloc)
    , torque_limit(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _drive_ids_type;
  _drive_ids_type drive_ids;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _velocity_limit_type;
  _velocity_limit_type velocity_limit;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _torque_limit_type;
  _torque_limit_type torque_limit;





  typedef boost::shared_ptr< ::melew3_msgs::SetLimitsMd80Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::melew3_msgs::SetLimitsMd80Request_<ContainerAllocator> const> ConstPtr;

}; // struct SetLimitsMd80Request_

typedef ::melew3_msgs::SetLimitsMd80Request_<std::allocator<void> > SetLimitsMd80Request;

typedef boost::shared_ptr< ::melew3_msgs::SetLimitsMd80Request > SetLimitsMd80RequestPtr;
typedef boost::shared_ptr< ::melew3_msgs::SetLimitsMd80Request const> SetLimitsMd80RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::melew3_msgs::SetLimitsMd80Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::melew3_msgs::SetLimitsMd80Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::melew3_msgs::SetLimitsMd80Request_<ContainerAllocator1> & lhs, const ::melew3_msgs::SetLimitsMd80Request_<ContainerAllocator2> & rhs)
{
  return lhs.drive_ids == rhs.drive_ids &&
    lhs.velocity_limit == rhs.velocity_limit &&
    lhs.torque_limit == rhs.torque_limit;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::melew3_msgs::SetLimitsMd80Request_<ContainerAllocator1> & lhs, const ::melew3_msgs::SetLimitsMd80Request_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace melew3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::SetLimitsMd80Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::SetLimitsMd80Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::SetLimitsMd80Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::SetLimitsMd80Request_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::SetLimitsMd80Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::SetLimitsMd80Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::melew3_msgs::SetLimitsMd80Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b6f95b7a29265a585ed64ff168463201";
  }

  static const char* value(const ::melew3_msgs::SetLimitsMd80Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb6f95b7a29265a58ULL;
  static const uint64_t static_value2 = 0x5ed64ff168463201ULL;
};

template<class ContainerAllocator>
struct DataType< ::melew3_msgs::SetLimitsMd80Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "melew3_msgs/SetLimitsMd80Request";
  }

  static const char* value(const ::melew3_msgs::SetLimitsMd80Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::melew3_msgs::SetLimitsMd80Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16[] drive_ids\n"
"float32[] velocity_limit\n"
"float32[] torque_limit\n"
;
  }

  static const char* value(const ::melew3_msgs::SetLimitsMd80Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::melew3_msgs::SetLimitsMd80Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.drive_ids);
      stream.next(m.velocity_limit);
      stream.next(m.torque_limit);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetLimitsMd80Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::melew3_msgs::SetLimitsMd80Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::melew3_msgs::SetLimitsMd80Request_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "drive_ids: ";
    if (v.drive_ids.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.drive_ids.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint16_t>::stream(s, true ? std::string() : indent + "    ", v.drive_ids[i]);
    }
    if (v.drive_ids.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "velocity_limit: ";
    if (v.velocity_limit.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.velocity_limit.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.velocity_limit[i]);
    }
    if (v.velocity_limit.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "torque_limit: ";
    if (v.torque_limit.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.torque_limit.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.torque_limit[i]);
    }
    if (v.torque_limit.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_SETLIMITSMD80REQUEST_H
