// Generated by gencpp from file melew3_msgs/SetModeMd80s.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_SETMODEMD80S_H
#define MELEW3_MSGS_MESSAGE_SETMODEMD80S_H

#include <ros/service_traits.h>


#include <melew3_msgs/SetModeMd80sRequest.h>
#include <melew3_msgs/SetModeMd80sResponse.h>


namespace melew3_msgs
{

struct SetModeMd80s
{

typedef SetModeMd80sRequest Request;
typedef SetModeMd80sResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetModeMd80s
} // namespace melew3_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::melew3_msgs::SetModeMd80s > {
  static const char* value()
  {
    return "631d9a748d9039ca34b51f2d88d432cb";
  }

  static const char* value(const ::melew3_msgs::SetModeMd80s&) { return value(); }
};

template<>
struct DataType< ::melew3_msgs::SetModeMd80s > {
  static const char* value()
  {
    return "melew3_msgs/SetModeMd80s";
  }

  static const char* value(const ::melew3_msgs::SetModeMd80s&) { return value(); }
};


// service_traits::MD5Sum< ::melew3_msgs::SetModeMd80sRequest> should match
// service_traits::MD5Sum< ::melew3_msgs::SetModeMd80s >
template<>
struct MD5Sum< ::melew3_msgs::SetModeMd80sRequest>
{
  static const char* value()
  {
    return MD5Sum< ::melew3_msgs::SetModeMd80s >::value();
  }
  static const char* value(const ::melew3_msgs::SetModeMd80sRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::melew3_msgs::SetModeMd80sRequest> should match
// service_traits::DataType< ::melew3_msgs::SetModeMd80s >
template<>
struct DataType< ::melew3_msgs::SetModeMd80sRequest>
{
  static const char* value()
  {
    return DataType< ::melew3_msgs::SetModeMd80s >::value();
  }
  static const char* value(const ::melew3_msgs::SetModeMd80sRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::melew3_msgs::SetModeMd80sResponse> should match
// service_traits::MD5Sum< ::melew3_msgs::SetModeMd80s >
template<>
struct MD5Sum< ::melew3_msgs::SetModeMd80sResponse>
{
  static const char* value()
  {
    return MD5Sum< ::melew3_msgs::SetModeMd80s >::value();
  }
  static const char* value(const ::melew3_msgs::SetModeMd80sResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::melew3_msgs::SetModeMd80sResponse> should match
// service_traits::DataType< ::melew3_msgs::SetModeMd80s >
template<>
struct DataType< ::melew3_msgs::SetModeMd80sResponse>
{
  static const char* value()
  {
    return DataType< ::melew3_msgs::SetModeMd80s >::value();
  }
  static const char* value(const ::melew3_msgs::SetModeMd80sResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_SETMODEMD80S_H
