// Generated by gencpp from file melew3_msgs/SetModeMd80sRequest.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_SETMODEMD80SREQUEST_H
#define MELEW3_MSGS_MESSAGE_SETMODEMD80SREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace melew3_msgs
{
template <class ContainerAllocator>
struct SetModeMd80sRequest_
{
  typedef SetModeMd80sRequest_<ContainerAllocator> Type;

  SetModeMd80sRequest_()
    : drive_ids()
    , mode()  {
    }
  SetModeMd80sRequest_(const ContainerAllocator& _alloc)
    : drive_ids(_alloc)
    , mode(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _drive_ids_type;
  _drive_ids_type drive_ids;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::melew3_msgs::SetModeMd80sRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::melew3_msgs::SetModeMd80sRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetModeMd80sRequest_

typedef ::melew3_msgs::SetModeMd80sRequest_<std::allocator<void> > SetModeMd80sRequest;

typedef boost::shared_ptr< ::melew3_msgs::SetModeMd80sRequest > SetModeMd80sRequestPtr;
typedef boost::shared_ptr< ::melew3_msgs::SetModeMd80sRequest const> SetModeMd80sRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::melew3_msgs::SetModeMd80sRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::melew3_msgs::SetModeMd80sRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::melew3_msgs::SetModeMd80sRequest_<ContainerAllocator1> & lhs, const ::melew3_msgs::SetModeMd80sRequest_<ContainerAllocator2> & rhs)
{
  return lhs.drive_ids == rhs.drive_ids &&
    lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::melew3_msgs::SetModeMd80sRequest_<ContainerAllocator1> & lhs, const ::melew3_msgs::SetModeMd80sRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace melew3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::SetModeMd80sRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::SetModeMd80sRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::SetModeMd80sRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::SetModeMd80sRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::SetModeMd80sRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::SetModeMd80sRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::melew3_msgs::SetModeMd80sRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "32851f8d0659651d7f7ff111ae45e731";
  }

  static const char* value(const ::melew3_msgs::SetModeMd80sRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x32851f8d0659651dULL;
  static const uint64_t static_value2 = 0x7f7ff111ae45e731ULL;
};

template<class ContainerAllocator>
struct DataType< ::melew3_msgs::SetModeMd80sRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "melew3_msgs/SetModeMd80sRequest";
  }

  static const char* value(const ::melew3_msgs::SetModeMd80sRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::melew3_msgs::SetModeMd80sRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16[] drive_ids\n"
"string[] mode\n"
;
  }

  static const char* value(const ::melew3_msgs::SetModeMd80sRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::melew3_msgs::SetModeMd80sRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.drive_ids);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetModeMd80sRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::melew3_msgs::SetModeMd80sRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::melew3_msgs::SetModeMd80sRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "drive_ids: ";
    if (v.drive_ids.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.drive_ids.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint16_t>::stream(s, true ? std::string() : indent + "    ", v.drive_ids[i]);
    }
    if (v.drive_ids.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mode: ";
    if (v.mode.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.mode.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.mode[i]);
    }
    if (v.mode.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_SETMODEMD80SREQUEST_H
