// Generated by gencpp from file melew3_msgs/waypoint.msg
// DO NOT EDIT!


#ifndef MELEW3_MSGS_MESSAGE_WAYPOINT_H
#define MELEW3_MSGS_MESSAGE_WAYPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Float64.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <std_msgs/Float64.h>
#include <std_msgs/Float64.h>
#include <std_msgs/Float64.h>

namespace melew3_msgs
{
template <class ContainerAllocator>
struct waypoint_
{
  typedef waypoint_<ContainerAllocator> Type;

  waypoint_()
    : header()
    , time()
    , position()
    , velocity()
    , acceleration()
    , yaw_position()
    , yaw_velocity()
    , yaw_acceleration()  {
    }
  waypoint_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , time(_alloc)
    , position(_alloc)
    , velocity(_alloc)
    , acceleration(_alloc)
    , yaw_position(_alloc)
    , yaw_velocity(_alloc)
    , yaw_acceleration(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _time_type;
  _time_type time;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _acceleration_type;
  _acceleration_type acceleration;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _yaw_position_type;
  _yaw_position_type yaw_position;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _yaw_velocity_type;
  _yaw_velocity_type yaw_velocity;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _yaw_acceleration_type;
  _yaw_acceleration_type yaw_acceleration;





  typedef boost::shared_ptr< ::melew3_msgs::waypoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::melew3_msgs::waypoint_<ContainerAllocator> const> ConstPtr;

}; // struct waypoint_

typedef ::melew3_msgs::waypoint_<std::allocator<void> > waypoint;

typedef boost::shared_ptr< ::melew3_msgs::waypoint > waypointPtr;
typedef boost::shared_ptr< ::melew3_msgs::waypoint const> waypointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::melew3_msgs::waypoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::melew3_msgs::waypoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::melew3_msgs::waypoint_<ContainerAllocator1> & lhs, const ::melew3_msgs::waypoint_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.time == rhs.time &&
    lhs.position == rhs.position &&
    lhs.velocity == rhs.velocity &&
    lhs.acceleration == rhs.acceleration &&
    lhs.yaw_position == rhs.yaw_position &&
    lhs.yaw_velocity == rhs.yaw_velocity &&
    lhs.yaw_acceleration == rhs.yaw_acceleration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::melew3_msgs::waypoint_<ContainerAllocator1> & lhs, const ::melew3_msgs::waypoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace melew3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::waypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::melew3_msgs::waypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::waypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melew3_msgs::waypoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::waypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melew3_msgs::waypoint_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::melew3_msgs::waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c206810b38430fa29a10e74179d3b4cd";
  }

  static const char* value(const ::melew3_msgs::waypoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc206810b38430fa2ULL;
  static const uint64_t static_value2 = 0x9a10e74179d3b4cdULL;
};

template<class ContainerAllocator>
struct DataType< ::melew3_msgs::waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "melew3_msgs/waypoint";
  }

  static const char* value(const ::melew3_msgs::waypoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::melew3_msgs::waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"std_msgs/Float64 time # 時刻\n"
"geometry_msgs/Point position # 位置\n"
"geometry_msgs/Point velocity # 速度\n"
"geometry_msgs/Point acceleration # 加速度\n"
"std_msgs/Float64 yaw_position # 操舵角\n"
"std_msgs/Float64 yaw_velocity # 操舵角速度\n"
"std_msgs/Float64 yaw_acceleration # 操舵角加速度\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::melew3_msgs::waypoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::melew3_msgs::waypoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.time);
      stream.next(m.position);
      stream.next(m.velocity);
      stream.next(m.acceleration);
      stream.next(m.yaw_position);
      stream.next(m.yaw_velocity);
      stream.next(m.yaw_acceleration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct waypoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::melew3_msgs::waypoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::melew3_msgs::waypoint_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "time: ";
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "position: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "velocity: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "acceleration: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.acceleration);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw_position: ";
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.yaw_position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw_velocity: ";
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.yaw_velocity);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw_acceleration: ";
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.yaw_acceleration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MELEW3_MSGS_MESSAGE_WAYPOINT_H
