//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the MELEW3_control package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __MELEW3_control__JOINT_PD_GAINCONFIG_H__
#define __MELEW3_control__JOINT_PD_GAINCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace MELEW3_control
{
  class joint_pd_gainConfigStatics;

  class joint_pd_gainConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(joint_pd_gainConfig &config, const joint_pd_gainConfig &max, const joint_pd_gainConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const joint_pd_gainConfig &config1, const joint_pd_gainConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, joint_pd_gainConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const joint_pd_gainConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, joint_pd_gainConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const joint_pd_gainConfig &config) const = 0;
      virtual void getValue(const joint_pd_gainConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T joint_pd_gainConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T joint_pd_gainConfig::* field;

      virtual void clamp(joint_pd_gainConfig &config, const joint_pd_gainConfig &max, const joint_pd_gainConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const joint_pd_gainConfig &config1, const joint_pd_gainConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, joint_pd_gainConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const joint_pd_gainConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, joint_pd_gainConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const joint_pd_gainConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const joint_pd_gainConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, joint_pd_gainConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, joint_pd_gainConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<joint_pd_gainConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(joint_pd_gainConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("Send"==(*_i)->name){Send = boost::any_cast<bool>(val);}
        if("FL1_motor_Kp"==(*_i)->name){FL1_motor_Kp = boost::any_cast<double>(val);}
        if("FL1_motor_Kd"==(*_i)->name){FL1_motor_Kd = boost::any_cast<double>(val);}
        if("FL2_motor_Kp"==(*_i)->name){FL2_motor_Kp = boost::any_cast<double>(val);}
        if("FL2_motor_Kd"==(*_i)->name){FL2_motor_Kd = boost::any_cast<double>(val);}
        if("FL3_motor_Kp"==(*_i)->name){FL3_motor_Kp = boost::any_cast<double>(val);}
        if("FL3_motor_Kd"==(*_i)->name){FL3_motor_Kd = boost::any_cast<double>(val);}
        if("FL4_motor_Kp"==(*_i)->name){FL4_motor_Kp = boost::any_cast<double>(val);}
        if("FL4_motor_Kd"==(*_i)->name){FL4_motor_Kd = boost::any_cast<double>(val);}
        if("FR1_motor_Kp"==(*_i)->name){FR1_motor_Kp = boost::any_cast<double>(val);}
        if("FR1_motor_Kd"==(*_i)->name){FR1_motor_Kd = boost::any_cast<double>(val);}
        if("FR2_motor_Kp"==(*_i)->name){FR2_motor_Kp = boost::any_cast<double>(val);}
        if("FR2_motor_Kd"==(*_i)->name){FR2_motor_Kd = boost::any_cast<double>(val);}
        if("FR3_motor_Kp"==(*_i)->name){FR3_motor_Kp = boost::any_cast<double>(val);}
        if("FR3_motor_Kd"==(*_i)->name){FR3_motor_Kd = boost::any_cast<double>(val);}
        if("FR4_motor_Kp"==(*_i)->name){FR4_motor_Kp = boost::any_cast<double>(val);}
        if("FR4_motor_Kd"==(*_i)->name){FR4_motor_Kd = boost::any_cast<double>(val);}
        if("BL1_motor_Kp"==(*_i)->name){BL1_motor_Kp = boost::any_cast<double>(val);}
        if("BL1_motor_Kd"==(*_i)->name){BL1_motor_Kd = boost::any_cast<double>(val);}
        if("BL2_motor_Kp"==(*_i)->name){BL2_motor_Kp = boost::any_cast<double>(val);}
        if("BL2_motor_Kd"==(*_i)->name){BL2_motor_Kd = boost::any_cast<double>(val);}
        if("BL3_motor_Kp"==(*_i)->name){BL3_motor_Kp = boost::any_cast<double>(val);}
        if("BL3_motor_Kd"==(*_i)->name){BL3_motor_Kd = boost::any_cast<double>(val);}
        if("BL4_motor_Kp"==(*_i)->name){BL4_motor_Kp = boost::any_cast<double>(val);}
        if("BL4_motor_Kd"==(*_i)->name){BL4_motor_Kd = boost::any_cast<double>(val);}
        if("BR1_motor_Kp"==(*_i)->name){BR1_motor_Kp = boost::any_cast<double>(val);}
        if("BR1_motor_Kd"==(*_i)->name){BR1_motor_Kd = boost::any_cast<double>(val);}
        if("BR2_motor_Kp"==(*_i)->name){BR2_motor_Kp = boost::any_cast<double>(val);}
        if("BR2_motor_Kd"==(*_i)->name){BR2_motor_Kd = boost::any_cast<double>(val);}
        if("BR3_motor_Kp"==(*_i)->name){BR3_motor_Kp = boost::any_cast<double>(val);}
        if("BR3_motor_Kd"==(*_i)->name){BR3_motor_Kd = boost::any_cast<double>(val);}
        if("BR4_motor_Kp"==(*_i)->name){BR4_motor_Kp = boost::any_cast<double>(val);}
        if("BR4_motor_Kd"==(*_i)->name){BR4_motor_Kd = boost::any_cast<double>(val);}
        if("wheel_FL_motor_Kp"==(*_i)->name){wheel_FL_motor_Kp = boost::any_cast<double>(val);}
        if("wheel_FL_motor_Kd"==(*_i)->name){wheel_FL_motor_Kd = boost::any_cast<double>(val);}
        if("wheel_FR_motor_Kp"==(*_i)->name){wheel_FR_motor_Kp = boost::any_cast<double>(val);}
        if("wheel_FR_motor_Kd"==(*_i)->name){wheel_FR_motor_Kd = boost::any_cast<double>(val);}
        if("wheel_BL_motor_Kp"==(*_i)->name){wheel_BL_motor_Kp = boost::any_cast<double>(val);}
        if("wheel_BL_motor_Kd"==(*_i)->name){wheel_BL_motor_Kd = boost::any_cast<double>(val);}
        if("wheel_BR_motor_Kp"==(*_i)->name){wheel_BR_motor_Kp = boost::any_cast<double>(val);}
        if("wheel_BR_motor_Kd"==(*_i)->name){wheel_BR_motor_Kd = boost::any_cast<double>(val);}
      }
    }

    bool Send;
double FL1_motor_Kp;
double FL1_motor_Kd;
double FL2_motor_Kp;
double FL2_motor_Kd;
double FL3_motor_Kp;
double FL3_motor_Kd;
double FL4_motor_Kp;
double FL4_motor_Kd;
double FR1_motor_Kp;
double FR1_motor_Kd;
double FR2_motor_Kp;
double FR2_motor_Kd;
double FR3_motor_Kp;
double FR3_motor_Kd;
double FR4_motor_Kp;
double FR4_motor_Kd;
double BL1_motor_Kp;
double BL1_motor_Kd;
double BL2_motor_Kp;
double BL2_motor_Kd;
double BL3_motor_Kp;
double BL3_motor_Kd;
double BL4_motor_Kp;
double BL4_motor_Kd;
double BR1_motor_Kp;
double BR1_motor_Kd;
double BR2_motor_Kp;
double BR2_motor_Kd;
double BR3_motor_Kp;
double BR3_motor_Kd;
double BR4_motor_Kp;
double BR4_motor_Kd;
double wheel_FL_motor_Kp;
double wheel_FL_motor_Kd;
double wheel_FR_motor_Kp;
double wheel_FR_motor_Kd;
double wheel_BL_motor_Kp;
double wheel_BL_motor_Kd;
double wheel_BR_motor_Kp;
double wheel_BR_motor_Kd;

    bool state;
    std::string name;

    
}groups;



//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool Send;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double FL1_motor_Kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double FL1_motor_Kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double FL2_motor_Kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double FL2_motor_Kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double FL3_motor_Kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double FL3_motor_Kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double FL4_motor_Kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double FL4_motor_Kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double FR1_motor_Kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double FR1_motor_Kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double FR2_motor_Kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double FR2_motor_Kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double FR3_motor_Kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double FR3_motor_Kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double FR4_motor_Kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double FR4_motor_Kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double BL1_motor_Kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double BL1_motor_Kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double BL2_motor_Kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double BL2_motor_Kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double BL3_motor_Kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double BL3_motor_Kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double BL4_motor_Kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double BL4_motor_Kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double BR1_motor_Kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double BR1_motor_Kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double BR2_motor_Kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double BR2_motor_Kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double BR3_motor_Kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double BR3_motor_Kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double BR4_motor_Kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double BR4_motor_Kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double wheel_FL_motor_Kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double wheel_FL_motor_Kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double wheel_FR_motor_Kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double wheel_FR_motor_Kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double wheel_BL_motor_Kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double wheel_BL_motor_Kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double wheel_BR_motor_Kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double wheel_BR_motor_Kd;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("joint_pd_gainConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (size_t i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (size_t i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (size_t i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (size_t i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const joint_pd_gainConfig &__max__ = __getMax__();
      const joint_pd_gainConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const joint_pd_gainConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const joint_pd_gainConfig &__getDefault__();
    static const joint_pd_gainConfig &__getMax__();
    static const joint_pd_gainConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const joint_pd_gainConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void joint_pd_gainConfig::ParamDescription<std::string>::clamp(joint_pd_gainConfig &config, const joint_pd_gainConfig &max, const joint_pd_gainConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class joint_pd_gainConfigStatics
  {
    friend class joint_pd_gainConfig;

    joint_pd_gainConfigStatics()
    {
joint_pd_gainConfig::GroupDescription<joint_pd_gainConfig::DEFAULT, joint_pd_gainConfig> Default("Default", "", 0, 0, true, &joint_pd_gainConfig::groups);
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Send = 0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Send = 1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Send = 0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<bool>("Send", "bool", 0, "Send impedance_command", "", &joint_pd_gainConfig::Send)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<bool>("Send", "bool", 0, "Send impedance_command", "", &joint_pd_gainConfig::Send)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.FL1_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.FL1_motor_Kp = 500.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.FL1_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FL1_motor_Kp", "double", 0, "P gain of FL1_motor joint", "", &joint_pd_gainConfig::FL1_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FL1_motor_Kp", "double", 0, "P gain of FL1_motor joint", "", &joint_pd_gainConfig::FL1_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.FL1_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.FL1_motor_Kd = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.FL1_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FL1_motor_Kd", "double", 0, "D gain of FL1_motor joint", "", &joint_pd_gainConfig::FL1_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FL1_motor_Kd", "double", 0, "D gain of FL1_motor joint", "", &joint_pd_gainConfig::FL1_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.FL2_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.FL2_motor_Kp = 500.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.FL2_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FL2_motor_Kp", "double", 0, "P gain of FL2_motor joint", "", &joint_pd_gainConfig::FL2_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FL2_motor_Kp", "double", 0, "P gain of FL2_motor joint", "", &joint_pd_gainConfig::FL2_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.FL2_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.FL2_motor_Kd = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.FL2_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FL2_motor_Kd", "double", 0, "D gain of FL2_motor joint", "", &joint_pd_gainConfig::FL2_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FL2_motor_Kd", "double", 0, "D gain of FL2_motor joint", "", &joint_pd_gainConfig::FL2_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.FL3_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.FL3_motor_Kp = 500.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.FL3_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FL3_motor_Kp", "double", 0, "P gain of FL3_motor joint", "", &joint_pd_gainConfig::FL3_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FL3_motor_Kp", "double", 0, "P gain of FL3_motor joint", "", &joint_pd_gainConfig::FL3_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.FL3_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.FL3_motor_Kd = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.FL3_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FL3_motor_Kd", "double", 0, "D gain of FL3_motor joint", "", &joint_pd_gainConfig::FL3_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FL3_motor_Kd", "double", 0, "D gain of FL3_motor joint", "", &joint_pd_gainConfig::FL3_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.FL4_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.FL4_motor_Kp = 500.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.FL4_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FL4_motor_Kp", "double", 0, "P gain of FL4_motor joint", "", &joint_pd_gainConfig::FL4_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FL4_motor_Kp", "double", 0, "P gain of FL4_motor joint", "", &joint_pd_gainConfig::FL4_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.FL4_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.FL4_motor_Kd = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.FL4_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FL4_motor_Kd", "double", 0, "D gain of FL4_motor joint", "", &joint_pd_gainConfig::FL4_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FL4_motor_Kd", "double", 0, "D gain of FL4_motor joint", "", &joint_pd_gainConfig::FL4_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.FR1_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.FR1_motor_Kp = 500.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.FR1_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FR1_motor_Kp", "double", 0, "P gain of FR1_motor joint", "", &joint_pd_gainConfig::FR1_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FR1_motor_Kp", "double", 0, "P gain of FR1_motor joint", "", &joint_pd_gainConfig::FR1_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.FR1_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.FR1_motor_Kd = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.FR1_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FR1_motor_Kd", "double", 0, "D gain of FR1_motor joint", "", &joint_pd_gainConfig::FR1_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FR1_motor_Kd", "double", 0, "D gain of FR1_motor joint", "", &joint_pd_gainConfig::FR1_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.FR2_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.FR2_motor_Kp = 500.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.FR2_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FR2_motor_Kp", "double", 0, "P gain of FR2_motor joint", "", &joint_pd_gainConfig::FR2_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FR2_motor_Kp", "double", 0, "P gain of FR2_motor joint", "", &joint_pd_gainConfig::FR2_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.FR2_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.FR2_motor_Kd = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.FR2_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FR2_motor_Kd", "double", 0, "D gain of FR2_motor joint", "", &joint_pd_gainConfig::FR2_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FR2_motor_Kd", "double", 0, "D gain of FR2_motor joint", "", &joint_pd_gainConfig::FR2_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.FR3_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.FR3_motor_Kp = 500.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.FR3_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FR3_motor_Kp", "double", 0, "P gain of FR3_motor joint", "", &joint_pd_gainConfig::FR3_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FR3_motor_Kp", "double", 0, "P gain of FR3_motor joint", "", &joint_pd_gainConfig::FR3_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.FR3_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.FR3_motor_Kd = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.FR3_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FR3_motor_Kd", "double", 0, "D gain of FR3_motor joint", "", &joint_pd_gainConfig::FR3_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FR3_motor_Kd", "double", 0, "D gain of FR3_motor joint", "", &joint_pd_gainConfig::FR3_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.FR4_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.FR4_motor_Kp = 500.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.FR4_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FR4_motor_Kp", "double", 0, "P gain of FR4_motor joint", "", &joint_pd_gainConfig::FR4_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FR4_motor_Kp", "double", 0, "P gain of FR4_motor joint", "", &joint_pd_gainConfig::FR4_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.FR4_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.FR4_motor_Kd = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.FR4_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FR4_motor_Kd", "double", 0, "D gain of FR4_motor joint", "", &joint_pd_gainConfig::FR4_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("FR4_motor_Kd", "double", 0, "D gain of FR4_motor joint", "", &joint_pd_gainConfig::FR4_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.BL1_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.BL1_motor_Kp = 500.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.BL1_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BL1_motor_Kp", "double", 0, "P gain of BL1_motor joint", "", &joint_pd_gainConfig::BL1_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BL1_motor_Kp", "double", 0, "P gain of BL1_motor joint", "", &joint_pd_gainConfig::BL1_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.BL1_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.BL1_motor_Kd = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.BL1_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BL1_motor_Kd", "double", 0, "D gain of BL1_motor joint", "", &joint_pd_gainConfig::BL1_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BL1_motor_Kd", "double", 0, "D gain of BL1_motor joint", "", &joint_pd_gainConfig::BL1_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.BL2_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.BL2_motor_Kp = 500.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.BL2_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BL2_motor_Kp", "double", 0, "P gain of BL2_motor joint", "", &joint_pd_gainConfig::BL2_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BL2_motor_Kp", "double", 0, "P gain of BL2_motor joint", "", &joint_pd_gainConfig::BL2_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.BL2_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.BL2_motor_Kd = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.BL2_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BL2_motor_Kd", "double", 0, "D gain of BL2_motor joint", "", &joint_pd_gainConfig::BL2_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BL2_motor_Kd", "double", 0, "D gain of BL2_motor joint", "", &joint_pd_gainConfig::BL2_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.BL3_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.BL3_motor_Kp = 500.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.BL3_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BL3_motor_Kp", "double", 0, "P gain of BL3_motor joint", "", &joint_pd_gainConfig::BL3_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BL3_motor_Kp", "double", 0, "P gain of BL3_motor joint", "", &joint_pd_gainConfig::BL3_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.BL3_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.BL3_motor_Kd = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.BL3_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BL3_motor_Kd", "double", 0, "D gain of BL3_motor joint", "", &joint_pd_gainConfig::BL3_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BL3_motor_Kd", "double", 0, "D gain of BL3_motor joint", "", &joint_pd_gainConfig::BL3_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.BL4_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.BL4_motor_Kp = 500.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.BL4_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BL4_motor_Kp", "double", 0, "P gain of BL4_motor joint", "", &joint_pd_gainConfig::BL4_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BL4_motor_Kp", "double", 0, "P gain of BL4_motor joint", "", &joint_pd_gainConfig::BL4_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.BL4_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.BL4_motor_Kd = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.BL4_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BL4_motor_Kd", "double", 0, "D gain of BL4_motor joint", "", &joint_pd_gainConfig::BL4_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BL4_motor_Kd", "double", 0, "D gain of BL4_motor joint", "", &joint_pd_gainConfig::BL4_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.BR1_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.BR1_motor_Kp = 500.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.BR1_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BR1_motor_Kp", "double", 0, "P gain of BR1_motor joint", "", &joint_pd_gainConfig::BR1_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BR1_motor_Kp", "double", 0, "P gain of BR1_motor joint", "", &joint_pd_gainConfig::BR1_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.BR1_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.BR1_motor_Kd = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.BR1_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BR1_motor_Kd", "double", 0, "D gain of BR1_motor joint", "", &joint_pd_gainConfig::BR1_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BR1_motor_Kd", "double", 0, "D gain of BR1_motor joint", "", &joint_pd_gainConfig::BR1_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.BR2_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.BR2_motor_Kp = 500.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.BR2_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BR2_motor_Kp", "double", 0, "P gain of BR2_motor joint", "", &joint_pd_gainConfig::BR2_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BR2_motor_Kp", "double", 0, "P gain of BR2_motor joint", "", &joint_pd_gainConfig::BR2_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.BR2_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.BR2_motor_Kd = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.BR2_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BR2_motor_Kd", "double", 0, "D gain of BR2_motor joint", "", &joint_pd_gainConfig::BR2_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BR2_motor_Kd", "double", 0, "D gain of BR2_motor joint", "", &joint_pd_gainConfig::BR2_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.BR3_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.BR3_motor_Kp = 500.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.BR3_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BR3_motor_Kp", "double", 0, "P gain of BR3_motor joint", "", &joint_pd_gainConfig::BR3_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BR3_motor_Kp", "double", 0, "P gain of BR3_motor joint", "", &joint_pd_gainConfig::BR3_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.BR3_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.BR3_motor_Kd = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.BR3_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BR3_motor_Kd", "double", 0, "D gain of BR3_motor joint", "", &joint_pd_gainConfig::BR3_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BR3_motor_Kd", "double", 0, "D gain of BR3_motor joint", "", &joint_pd_gainConfig::BR3_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.BR4_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.BR4_motor_Kp = 500.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.BR4_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BR4_motor_Kp", "double", 0, "P gain of BR4_motor joint", "", &joint_pd_gainConfig::BR4_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BR4_motor_Kp", "double", 0, "P gain of BR4_motor joint", "", &joint_pd_gainConfig::BR4_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.BR4_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.BR4_motor_Kd = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.BR4_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BR4_motor_Kd", "double", 0, "D gain of BR4_motor joint", "", &joint_pd_gainConfig::BR4_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("BR4_motor_Kd", "double", 0, "D gain of BR4_motor joint", "", &joint_pd_gainConfig::BR4_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.wheel_FL_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.wheel_FL_motor_Kp = 500.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.wheel_FL_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("wheel_FL_motor_Kp", "double", 0, "P gain of wheel_FL_motor joint", "", &joint_pd_gainConfig::wheel_FL_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("wheel_FL_motor_Kp", "double", 0, "P gain of wheel_FL_motor joint", "", &joint_pd_gainConfig::wheel_FL_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.wheel_FL_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.wheel_FL_motor_Kd = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.wheel_FL_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("wheel_FL_motor_Kd", "double", 0, "D gain of wheel_FL_motor joint", "", &joint_pd_gainConfig::wheel_FL_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("wheel_FL_motor_Kd", "double", 0, "D gain of wheel_FL_motor joint", "", &joint_pd_gainConfig::wheel_FL_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.wheel_FR_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.wheel_FR_motor_Kp = 500.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.wheel_FR_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("wheel_FR_motor_Kp", "double", 0, "P gain of wheel_FR_motor joint", "", &joint_pd_gainConfig::wheel_FR_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("wheel_FR_motor_Kp", "double", 0, "P gain of wheel_FR_motor joint", "", &joint_pd_gainConfig::wheel_FR_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.wheel_FR_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.wheel_FR_motor_Kd = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.wheel_FR_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("wheel_FR_motor_Kd", "double", 0, "D gain of wheel_FR_motor joint", "", &joint_pd_gainConfig::wheel_FR_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("wheel_FR_motor_Kd", "double", 0, "D gain of wheel_FR_motor joint", "", &joint_pd_gainConfig::wheel_FR_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.wheel_BL_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.wheel_BL_motor_Kp = 500.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.wheel_BL_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("wheel_BL_motor_Kp", "double", 0, "P gain of wheel_BL_motor joint", "", &joint_pd_gainConfig::wheel_BL_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("wheel_BL_motor_Kp", "double", 0, "P gain of wheel_BL_motor joint", "", &joint_pd_gainConfig::wheel_BL_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.wheel_BL_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.wheel_BL_motor_Kd = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.wheel_BL_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("wheel_BL_motor_Kd", "double", 0, "D gain of wheel_BL_motor joint", "", &joint_pd_gainConfig::wheel_BL_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("wheel_BL_motor_Kd", "double", 0, "D gain of wheel_BL_motor joint", "", &joint_pd_gainConfig::wheel_BL_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.wheel_BR_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.wheel_BR_motor_Kp = 500.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.wheel_BR_motor_Kp = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("wheel_BR_motor_Kp", "double", 0, "P gain of wheel_BR_motor joint", "", &joint_pd_gainConfig::wheel_BR_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("wheel_BR_motor_Kp", "double", 0, "P gain of wheel_BR_motor joint", "", &joint_pd_gainConfig::wheel_BR_motor_Kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.wheel_BR_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.wheel_BR_motor_Kd = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.wheel_BR_motor_Kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("wheel_BR_motor_Kd", "double", 0, "D gain of wheel_BR_motor joint", "", &joint_pd_gainConfig::wheel_BR_motor_Kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(joint_pd_gainConfig::AbstractParamDescriptionConstPtr(new joint_pd_gainConfig::ParamDescription<double>("wheel_BR_motor_Kd", "double", 0, "D gain of wheel_BR_motor joint", "", &joint_pd_gainConfig::wheel_BR_motor_Kd)));
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(joint_pd_gainConfig::AbstractGroupDescriptionConstPtr(new joint_pd_gainConfig::GroupDescription<joint_pd_gainConfig::DEFAULT, joint_pd_gainConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<joint_pd_gainConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<joint_pd_gainConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<joint_pd_gainConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    joint_pd_gainConfig __max__;
    joint_pd_gainConfig __min__;
    joint_pd_gainConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const joint_pd_gainConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static joint_pd_gainConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &joint_pd_gainConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const joint_pd_gainConfig &joint_pd_gainConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const joint_pd_gainConfig &joint_pd_gainConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const joint_pd_gainConfig &joint_pd_gainConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<joint_pd_gainConfig::AbstractParamDescriptionConstPtr> &joint_pd_gainConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<joint_pd_gainConfig::AbstractGroupDescriptionConstPtr> &joint_pd_gainConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const joint_pd_gainConfigStatics *joint_pd_gainConfig::__get_statics__()
  {
    const static joint_pd_gainConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = joint_pd_gainConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __JOINT_PD_GAINRECONFIGURATOR_H__
