waypoint_ref:
  - ID: 0 # ID
    send_time: 0.0 # 送信時刻
    time: 12.0 # 時刻
    position: [ 11.0, 1.0, 0.41441016151 ] # 目標位置 (ZMPのx座標, ZMPのy座標, 重心高さ)
    velocity: [ 0.0, 0.0, 0.0 ] # 目標速度
    acceleration: [ 0.0, 0.0, 0.0] # 目標加速度
    yaw_position: 0.0 # 目標重心操舵角
    yaw_velocity: 0.0 # 目標重心操舵角速度
    yaw_acceleration: 0.0 # 目標重心操舵角加速度
