FL1_motor_position_controller:
  joint: FL1_motor
  config: # モータの設定
    can_id: 11
    model: AK80-9
    Kp: 500.0
    Kd: 2.5
    offset: -65.0  # [deg]
    inverseDirection: false
    joint_limit: [-65.0, 60.0] #[deg]
    max_output: 75.0 # [Nm]

FL2_motor_position_controller:
  joint: FL2_motor
  config:
    can_id: 12
    model: AK80-9
    Kp: 500.0
    Kd: 2.5
    offset: -65.0  # [deg]
    inverseDirection: false
    joint_limit: [-65.0, 60.0] # [deg]
    max_output: 75.0 # [Nm]

FL3_motor_position_controller:
  joint: FL3_motor
  config:
    can_id: 13
    model: AK80-9
    Kp: 500.0
    Kd: 2.5
    offset: -65.0  # [deg]
    inverseDirection: true
    joint_limit: [-65.0, 60.0] # [deg]
    max_output: 75.0 # [Nm]

FL4_motor_position_controller:
  joint: FL4_motor
  config:
    can_id: 14
    model: AK80-9
    Kp: 500.0
    Kd: 2.5
    offset: -65.0  # [deg]
    inverseDirection: true
    joint_limit: [-65.0, 60.0] # [deg]
    max_output: 75.0 # [Nm]

FR1_motor_position_controller:
  joint: FR1_motor
  config: # モータの設定
    can_id: 15
    model: AK80-9
    Kp: 500.0
    Kd: 2.5
    offset: -65.0  # [deg]
    inverseDirection: false
    joint_limit: [-65.0, 60.0] #[deg]
    max_output: 75.0 # [Nm]

FR2_motor_position_controller:
  joint: FR2_motor
  config:
    can_id: 16
    model: AK80-9
    Kp: 500.0
    Kd: 2.5
    offset: -65.0  # [deg]
    inverseDirection: false
    joint_limit: [-65.0, 60.0] # [deg]
    max_output: 75.0 # [Nm]

FR3_motor_position_controller:
  joint: FR3_motor
  config:
    can_id: 17
    model: AK80-9
    Kp: 500.0
    Kd: 2.5
    offset: -65.0  # [deg]
    inverseDirection: true
    joint_limit: [-65.0, 60.0] # [deg]
    max_output: 75.0 # [Nm]

FR4_motor_position_controller:
  joint: FR4_motor
  config:
    can_id: 18
    model: AK80-9
    Kp: 500.0
    Kd: 2.5
    offset: -65.0  # [deg]
    inverseDirection: true
    joint_limit: [-65.0, 60.0] # [deg]
    max_output: 75.0 # [Nm]

BL1_motor_position_controller:
  joint: BL1_motor
  config: # モータの設定
    can_id: 19
    model: AK80-9
    Kp: 500.0
    Kd: 2.5
    offset: 65.0  # [deg]
    inverseDirection: false
    joint_limit: [-60.0, 65.0] # [deg]
    max_output: 75.0 # [Nm]

BL2_motor_position_controller:
  joint: BL2_motor
  config:
    can_id: 20
    model: AK80-9
    Kp: 500.0
    Kd: 2.5
    offset: 65.0  # [deg]
    inverseDirection: false
    joint_limit: [-60.0, 65.0] # [deg]
    max_output: 75.0 # [Nm]

BL3_motor_position_controller:
  joint: BL3_motor
  config:
    can_id: 21
    model: AK80-9
    Kp: 500.0
    Kd: 2.5
    offset: 65.0  # [deg]
    inverseDirection: true
    joint_limit: [-60.0, 65.0] # [deg]
    max_output: 75.0 # [Nm]

BL4_motor_position_controller:
  joint: BL4_motor
  config:
    can_id: 22
    model: AK80-9
    Kp: 500.0
    Kd: 2.5
    offset: 65.0  # [deg]
    inverseDirection: true
    joint_limit: [-60.0, 65.0] # [deg]
    max_output: 75.0 # [Nm]

BR1_motor_position_controller:
  joint: BR1_motor
  config: # モータの設定
    can_id: 23
    model: AK80-9
    Kp: 500.0
    Kd: 2.5
    offset: 65.0  # [deg]
    inverseDirection: false
    joint_limit: [-60.0, 65.0] #[deg]
    max_output: 75.0 # [Nm]

BR2_motor_position_controller:
  joint: BR2_motor
  config:
    can_id: 24
    model: AK80-9
    Kp: 500.0
    Kd: 2.5
    offset: 65.0  # [deg]
    inverseDirection: false
    joint_limit: [-60.0, 65.0] # [deg]
    max_output: 75.0 # [Nm]

BR3_motor_position_controller:
  joint: BR3_motor
  config:
    can_id: 25
    model: AK80-9
    Kp: 500.0
    Kd: 2.5
    offset: 65.0  # [deg]
    inverseDirection: true
    joint_limit: [-60.0, 65.0] # [deg]
    max_output: 75.0 # [Nm]

BR4_motor_position_controller:
  joint: BR4_motor
  config:
    can_id: 26
    model: AK80-9
    Kp: 500.0
    Kd: 2.5
    offset: 65.0  # [deg]
    inverseDirection: true
    joint_limit: [-60.0, 65.0] # [deg]
    max_output: 75.0 # [Nm]

wheel_FL_motor_position_controller:
  joint: wheel_FL_motor
  config:
    can_id: 27
    model: AK80-9
    Kp: 0.0
    Kd: 4.0
    offset: 0.0  # [deg]
    inverseDirection: false
    max_output: 75.0 # [Nm]

wheel_FR_motor_position_controller:
  joint: wheel_FR_motor
  config:
    can_id: 28
    model: AK80-9
    Kp: 0.0
    Kd: 4.0
    offset: 0.0  # [deg]
    inverseDirection: true
    max_output: 75.0 # [Nm]

wheel_BL_motor_position_controller:
  joint: wheel_BL_motor
  config:
    can_id: 29
    model: AK80-9
    Kp: 0.0
    Kd: 4.0
    offset: 0.0  # [deg]
    inverseDirection: false
    max_output: 75.0 # [Nm]

wheel_BR_motor_position_controller:
  joint: wheel_BR_motor
  config:
    can_id: 30
    model: AK80-9
    Kp: 0.0
    Kd: 4.0
    offset: 0.0  # [deg]
    inverseDirection: true
    max_output: 75.0 # [Nm]