MELEW3:
  leg_FL_position_controller:
    type: effort_controllers/JointGroupPositionController
    joints:
      - HIP_YAW_FL
      - HIP_ROLL_FL
      - HIP_PITCH_FL
      - KNEE_FL
      
    HIP_YAW_FL:
      pid: {p: 1500.0, i: 0.0, d: 10.0}
    HIP_ROLL_FL:
      pid: {p: 1500.0, i: 0.0, d: 10.0}
    HIP_PITCH_FL:
      pid: {p: 1500.0, i: 0.0, d: 10.0}
    KNEE_FL:
      pid: {p: 1500.0, i: 0.0, d: 10.0}
  
  leg_FR_position_controller:
    type: effort_controllers/JointGroupPositionController
    joints:
      - HIP_YAW_FR
      - HIP_ROLL_FR
      - HIP_PITCH_FR
      - KNEE_FR
      
    HIP_YAW_FR:
      pid: {p: 1500.0, i: 0.0, d: 10.0}
    HIP_ROLL_FR:
      pid: {p: 1500.0, i: 0.0, d: 10.0}
    HIP_PITCH_FR:
      pid: {p: 1500.0, i: 0.0, d: 10.0}
    KNEE_FR:
      pid: {p: 1500.0, i: 0.0, d: 10.0}

  leg_BL_position_controller:
    type: effort_controllers/JointGroupPositionController
    joints:
      - HIP_YAW_BL
      - HIP_ROLL_BL
      - HIP_PITCH_BL
      - KNEE_BL
      
    HIP_YAW_BL:
      pid: {p: 1500.0, i: 0.0, d: 10.0}
    HIP_ROLL_BL:
      pid: {p: 1500.0, i: 0.0, d: 10.0}
    HIP_PITCH_BL:
      pid: {p: 1500.0, i: 0.0, d: 10.0}
    KNEE_BL:
      pid: {p: 1500.0, i: 0.0, d: 10.0}

  leg_BR_position_controller:
    type: effort_controllers/JointGroupPositionController
    joints:
      - HIP_YAW_BR
      - HIP_ROLL_BR
      - HIP_PITCH_BR
      - KNEE_BR

    HIP_YAW_BR:
      pid: {p: 1500.0, i: 0.0, d: 10.0}
    HIP_ROLL_BR:
      pid: {p: 1500.0, i: 0.0, d: 10.0}
    HIP_PITCH_BR:
      pid: {p: 1500.0, i: 0.0, d: 10.0}
    KNEE_BR:
      pid: {p: 1500.0, i: 0.0, d: 10.0}

  wheel_controller:
    type: effort_controllers/JointGroupPositionController
    joints:
      - WHEEL_FL
      - WHEEL_FR
      - WHEEL_BL
      - WHEEL_BR

    WHEEL_FL:
      pid: {p: 40.0, i: 0.0, d: 0.0}
    WHEEL_FR:
      pid: {p: 40.0, i: 0.0, d: 0.0}
    WHEEL_BL:
      pid: {p: 40.0, i: 0.0, d: 0.0}
    WHEEL_BR:
      pid: {p: 40.0, i: 0.0, d: 0.0}
      
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 1000