/sim_flag: false

/md80_FL/impedance_command_topic_name: /md80_FL/impedance_command
/md80_FR/impedance_command_topic_name: /md80_FR/impedance_command
/md80_BL/impedance_command_topic_name: /md80_BL/impedance_command
/md80_BR/impedance_command_topic_name: /md80_BR/impedance_command

/md80_FL/motion_command_topic_name: /md80_FL/motion_command
/md80_FR/motion_command_topic_name: /md80_FR/motion_command
/md80_BL/motion_command_topic_name: /md80_BL/motion_command
/md80_BR/motion_command_topic_name: /md80_BR/motion_command

/md80_FL/joint_states_topic_name: /md80_FL/joint_states
/md80_FR/joint_states_topic_name: /md80_FR/joint_states
/md80_BL/joint_states_topic_name: /md80_BL/joint_states
/md80_BR/joint_states_topic_name: /md80_BR/joint_states

/zero_md80s_FL_service_name: /zero_md80s_FL
/zero_md80s_FR_service_name: /zero_md80s_FR
/zero_md80s_BL_service_name: /zero_md80s_BL
/zero_md80s_BR_service_name: /zero_md80s_BR

/enable_md80s_FL_service_name: /enable_md80s_FL
/enable_md80s_FR_service_name: /enable_md80s_FR
/enable_md80s_BL_service_name: /enable_md80s_BL
/enable_md80s_BR_service_name: /enable_md80s_BR

/disable_md80s_FL_service_name: /disable_md80s_FL
/disable_md80s_FR_service_name: /disable_md80s_FR
/disable_md80s_BL_service_name: /disable_md80s_BL
/disable_md80s_BR_service_name: /disable_md80s_BR