MELEW3:
  link_info_FL:
    - ID: 1
      name: BODY_FL
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 2
      name: FL_A1
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 3
      name: FL_A2
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 4
      name: FL_A3
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 5
      name: FL_A4
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 6
      name: FL_B1
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 7
      name: FL_B2
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 8
      name: FL_B3
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 9
      name: FL_B4
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 10
      name: FL_C1
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 11
      name: FL_C2
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 12
      name: FL_D1
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 13
      name: FL_D2
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 14
      name: WHEEL_FL
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

  link_info_FR:
    - ID: 1
      name: BODY_FR
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 2
      name: FR_A1
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 3
      name: FR_A2
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 4
      name: FR_A3
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 5
      name: FR_A4
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 6
      name: FR_B1
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 7
      name: FR_B2
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 8
      name: FR_B3
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 9
      name: FR_B4
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 10
      name: FR_C1
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 11
      name: FR_C2
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 12
      name: FR_D1
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 13
      name: FR_D2
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 14
      name: WHEEL_FR
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

  link_info_BL:
    - ID: 1
      name: BODY_BL
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 2
      name: BL_A1
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 3
      name: BL_A2
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 4
      name: BL_A3
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 5
      name: BL_A4
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 6
      name: BL_B1
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 7
      name: BL_B2
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 8
      name: BL_B3
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 9
      name: BL_B4
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 10
      name: BL_C1
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 11
      name: BL_C2
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 12
      name: BL_D1
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 13
      name: BL_D2
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 14
      name: WHEEL_BL
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

  link_info_BR:
    - ID: 1
      name: BODY_BR
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 2
      name: BR_A1
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 3
      name: BR_A2
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 4
      name: BR_A3
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 5
      name: BR_A4
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 6
      name: BR_B1
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 7
      name: BR_B2
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 8
      name: BR_B3
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 9
      name: BR_B4
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 10
      name: BR_C1
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 11
      name: BR_C2
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 12
      name: BR_D1
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 13
      name: BR_D2
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 14
      name: WHEEL_BR
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

MELEW3_sim:
  link_info_FL:
    - ID: 1
      name: BODY_FL
      mass: 1.5 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 2
      name: HIP_YAW_FL
      mass: 0.05 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 3
      name: HIP_ROLL_FL
      mass: 0.10 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 4
      name: HIP_PITCH_FL
      mass: 4.05 #[kg]
      com: [0.0, 0.0, -0.1012345679012346] #[m]

    - ID: 5
      name: KNEE_FL
      mass: 1.0 #[kg]
      com: [0.0, 0.0, -0.10] #[m]

    - ID: 6
      name: WHEEL_FL
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

  link_info_FR:
    - ID: 1
      name: BODY_FR
      mass: 1.5 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 2
      name: HIP_YAW_FR
      mass: 0.05 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 3
      name: HIP_ROLL_FR
      mass: 0.10 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 4
      name: HIP_PITCH_FR
      mass: 4.05 #[kg]
      com: [0.0, 0.0, -0.1012345679012346] #[m]

    - ID: 5
      name: KNEE_FR
      mass: 1.0 #[kg]
      com: [0.0, 0.0, -0.10] #[m]

    - ID: 6
      name: WHEEL_FR
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

  link_info_BL:
    - ID: 1
      name: BODY_BL
      mass: 1.5 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 2
      name: HIP_YAW_BL
      mass: 0.05 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 3
      name: HIP_ROLL_BL
      mass: 0.10 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 4
      name: HIP_PITCH_BL
      mass: 4.05 #[kg]
      com: [0.0, 0.0, -0.1012345679012346] #[m]

    - ID: 5
      name: KNEE_BL
      mass: 1.0 #[kg]
      com: [0.0, 0.0, -0.10] #[m]

    - ID: 6
      name: WHEEL_BL
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

  link_info_BR:
    - ID: 1
      name: BODY_BR
      mass: 1.5 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 2
      name: HIP_YAW_BR
      mass: 0.05 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 3
      name: HIP_ROLL_BR
      mass: 0.10 #[kg]
      com: [0.0, 0.0, 0.0] #[m]

    - ID: 4
      name: HIP_PITCH_BR
      mass: 4.05 #[kg]
      com: [0.0, 0.0, -0.1012345679012346] #[m]

    - ID: 5
      name: KNEE_BR
      mass: 1.0 #[kg]
      com: [0.0, 0.0, -0.10] #[m]

    - ID: 6
      name: WHEEL_BR
      mass: 1.0 #[kg]
      com: [0.0, 0.0, 0.0] #[m]