# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from melew3_msgs/leg_info.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class leg_info(genpy.Message):
  _md5sum = "d4617fc0ec53327f436a5e22e15be77a"
  _type = "melew3_msgs/leg_info"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Point32 position
std_msgs/Float64 yaw
================================================================================
MSG: geometry_msgs/Point32
# This contains the position of a point in free space(with 32 bits of precision).
# It is recommeded to use Point wherever possible instead of Point32.  
# 
# This recommendation is to promote interoperability.  
#
# This message is designed to take up less space when sending
# lots of points at once, as in the case of a PointCloud.  

float32 x
float32 y
float32 z
================================================================================
MSG: std_msgs/Float64
float64 data"""
  __slots__ = ['position','yaw']
  _slot_types = ['geometry_msgs/Point32','std_msgs/Float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       position,yaw

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(leg_info, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.position is None:
        self.position = geometry_msgs.msg.Point32()
      if self.yaw is None:
        self.yaw = std_msgs.msg.Float64()
    else:
      self.position = geometry_msgs.msg.Point32()
      self.yaw = std_msgs.msg.Float64()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3fd().pack(_x.position.x, _x.position.y, _x.position.z, _x.yaw.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point32()
      if self.yaw is None:
        self.yaw = std_msgs.msg.Float64()
      end = 0
      _x = self
      start = end
      end += 20
      (_x.position.x, _x.position.y, _x.position.z, _x.yaw.data,) = _get_struct_3fd().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3fd().pack(_x.position.x, _x.position.y, _x.position.z, _x.yaw.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point32()
      if self.yaw is None:
        self.yaw = std_msgs.msg.Float64()
      end = 0
      _x = self
      start = end
      end += 20
      (_x.position.x, _x.position.y, _x.position.z, _x.yaw.data,) = _get_struct_3fd().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3fd = None
def _get_struct_3fd():
    global _struct_3fd
    if _struct_3fd is None:
        _struct_3fd = struct.Struct("<3fd")
    return _struct_3fd
